"""Middleware — layer barrel (generated, DOCTRINE §5.1)."""

from cara._LazyExports import _install_lazy_exports

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "AttachRequestID": (".http", "AttachRequestID"),
    "Authenticate": (".ws", "Authenticate"),
    "AuthenticateUser": (".http", "AuthenticateUser"),
    "AuthenticateUserOptional": (".http", "AuthenticateUserOptional"),
    "CORS_DEFAULTS": (".http", "CORS_DEFAULTS"),
    "CanPerform": (".http", "CanPerform"),
    "CheckMaintenanceMode": (".http", "CheckMaintenanceMode"),
    "CompressResponses": (".http", "CompressResponses"),
    "ConditionalGet": (".http", "ConditionalGet"),
    "EnforceBodySizeLimit": (".http", "EnforceBodySizeLimit"),
    "FilterBlockedUserAgents": (".http", "FilterBlockedUserAgents"),
    "HandleCors": (".http", "HandleCors"),
    "LogHttpRequests": (".http", "LogHttpRequests"),
    "LogWSRequests": (".ws", "LogWSRequests"),
    "Middleware": (".Middleware", "Middleware"),
    "MiddlewareCapsule": (".MiddlewareCapsule", "MiddlewareCapsule"),
    "MiddlewareParameterParser": (
        ".MiddlewareParameterParser",
        "MiddlewareParameterParser",
    ),
    "MiddlewareProvider": (".MiddlewareProvider", "MiddlewareProvider"),
    "MiddlewareRegistry": (".MiddlewareRegistry", "MiddlewareRegistry"),
    "PersistRequestLog": (".http", "PersistRequestLog"),
    "RecordPrometheusMetrics": (".http", "RecordPrometheusMetrics"),
    "RecordRequestMetrics": (".http", "RecordRequestMetrics"),
    "RequestLogStore": (".http", "RequestLogStore"),
    "ResetHttpAuth": (".http", "ResetHttpAuth"),
    "ResetWebSocketAuth": (".ws", "ResetWebSocketAuth"),
    "SecurityHeaders": (".http", "SecurityHeaders"),
    "ServeStaticFiles": (".http", "ServeStaticFiles"),
    "ShouldAuthenticate": (".http", "ShouldAuthenticate"),
    "Throttle": (".ws", "Throttle"),
    "ThrottleRequests": (".http", "ThrottleRequests"),
    "TraceRequests": (".http", "TraceRequests"),
    "TrimStrings": (".http", "TrimStrings"),
    "apply_cors_headers_to_response": (".http", "apply_cors_headers_to_response"),
    "denial_status": (".http", "denial_status"),
    "load_cors_policy": (".http", "load_cors_policy"),
    "origin_explicitly_allowed": (".http", "origin_explicitly_allowed"),
    "path_in_cors_scope": (".http", "path_in_cors_scope"),
    "resolve_allow_origin": (".http", "resolve_allow_origin"),
}

__all__ = [
    "AttachRequestID",
    "Authenticate",
    "AuthenticateUser",
    "AuthenticateUserOptional",
    "CORS_DEFAULTS",
    "CanPerform",
    "CheckMaintenanceMode",
    "CompressResponses",
    "ConditionalGet",
    "EnforceBodySizeLimit",
    "FilterBlockedUserAgents",
    "HandleCors",
    "LogHttpRequests",
    "LogWSRequests",
    "Middleware",
    "MiddlewareCapsule",
    "MiddlewareParameterParser",
    "MiddlewareProvider",
    "MiddlewareRegistry",
    "PersistRequestLog",
    "RecordPrometheusMetrics",
    "RecordRequestMetrics",
    "RequestLogStore",
    "ResetHttpAuth",
    "ResetWebSocketAuth",
    "SecurityHeaders",
    "ServeStaticFiles",
    "ShouldAuthenticate",
    "Throttle",
    "ThrottleRequests",
    "TraceRequests",
    "TrimStrings",
    "apply_cors_headers_to_response",
    "denial_status",
    "load_cors_policy",
    "origin_explicitly_allowed",
    "path_in_cors_scope",
    "resolve_allow_origin",
]

_install_lazy_exports(__name__, _LAZY_EXPORTS)
