"""Concrete command modules; import leaf commands explicitly."""

from cara._LazyExports import _install_lazy_exports

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "AMQPConnectionManager": (".AMQPConnectionManager", "AMQPConnectionManager"),
    "ActiveJobCancellationRegistry": (
        ".ActiveJobCancellationRegistry",
        "ActiveJobCancellationRegistry",
    ),
    "ArchBarrelsCommand": (".ArchBarrelsCommand", "ArchBarrelsCommand"),
    "ArchCheckCommand": (".ArchCheckCommand", "ArchCheckCommand"),
    "CacheClearCommand": (".CacheClearCommand", "CacheClearCommand"),
    "CheckResult": (".CheckResult", "CheckResult"),
    "DEFAULT_LOCK_TIMEOUT_MS": (".SchemaApplyCommand", "DEFAULT_LOCK_TIMEOUT_MS"),
    "DeliverySettlementError": (".DeliverySettlementError", "DeliverySettlementError"),
    "DevResetCommand": (".DevResetCommand", "DevResetCommand"),
    "DocsCommand": (".DocsCommand", "DocsCommand"),
    "DocsGenerateCommand": (".DocsGenerateCommand", "DocsGenerateCommand"),
    "DocsServeCommand": (".DocsServeCommand", "DocsServeCommand"),
    "DownCommand": (".DownCommand", "DownCommand"),
    "FAIL": (".CheckResult", "FAIL"),
    "GenerateKeyCommand": (".GenerateKeyCommand", "GenerateKeyCommand"),
    "JobProcessor": (".JobProcessor", "JobProcessor"),
    "ListCommandsCommand": (".ListCommandsCommand", "ListCommandsCommand"),
    "MakeControllerCommand": (".MakeControllerCommand", "MakeControllerCommand"),
    "MakeEventCommand": (".MakeEventCommand", "MakeEventCommand"),
    "MakeJobCommand": (".MakeJobCommand", "MakeJobCommand"),
    "MakeListenerCommand": (".MakeListenerCommand", "MakeListenerCommand"),
    "MakeMailCommand": (".MakeMailCommand", "MakeMailCommand"),
    "MakeMiddlewareCommand": (".MakeMiddlewareCommand", "MakeMiddlewareCommand"),
    "MakeMigrationCommand": (".MakeMigrationCommand", "MakeMigrationCommand"),
    "MakeModelCommand": (".MakeModelCommand", "MakeModelCommand"),
    "MakeNotificationCommand": (".MakeNotificationCommand", "MakeNotificationCommand"),
    "MakePolicyCommand": (".MakePolicyCommand", "MakePolicyCommand"),
    "MigrateBaselineCommand": (".MigrateBaselineCommand", "MigrateBaselineCommand"),
    "MigrateCommand": (".MigrateCommand", "MigrateCommand"),
    "MigrateResetCommand": (".MigrateResetCommand", "MigrateResetCommand"),
    "MigrateRollbackCommand": (".MigrateRollbackCommand", "MigrateRollbackCommand"),
    "MigrateStatusCommand": (".MigrateStatusCommand", "MigrateStatusCommand"),
    "MigrationFile": (".MigrationFile", "MigrationFile"),
    "MigrationsCheckCommand": (".MigrationsCheckCommand", "MigrationsCheckCommand"),
    "ModelPruneCommand": (".ModelPruneCommand", "ModelPruneCommand"),
    "OK": (".CheckResult", "OK"),
    "PreflightCommand": (".PreflightCommand", "PreflightCommand"),
    "QueueFlushCommand": (".QueueFlushCommand", "QueueFlushCommand"),
    "QueueHookCommand": (".QueueHookCommand", "QueueHookCommand"),
    "QueueHooksCommand": (".QueueHooksCommand", "QueueHooksCommand"),
    "QueueMonitorCommand": (".QueueMonitorCommand", "QueueMonitorCommand"),
    "QueuePurgeCommand": (".QueuePurgeCommand", "QueuePurgeCommand"),
    "QueueRelayCommand": (".QueueRelayCommand", "QueueRelayCommand"),
    "QueueRetryCommand": (".QueueRetryCommand", "QueueRetryCommand"),
    "QueueStatsCommand": (".QueueStatsCommand", "QueueStatsCommand"),
    "QueueWorkCommand": (".QueueWorkCommand", "QueueWorkCommand"),
    "RouteGeneratorCommand": (".RouteGeneratorCommand", "RouteGeneratorCommand"),
    "RouteListCommand": (".RouteListCommand", "RouteListCommand"),
    "ScheduleWorkCommand": (".ScheduleWorkCommand", "ScheduleWorkCommand"),
    "SchemaApplyCommand": (".SchemaApplyCommand", "SchemaApplyCommand"),
    "SchemaCheckCommand": (".SchemaCheckCommand", "SchemaCheckCommand"),
    "SchemaPlanCommand": (".SchemaPlanCommand", "SchemaPlanCommand"),
    "SchemaRollbackCommand": (".SchemaRollbackCommand", "SchemaRollbackCommand"),
    "SchemaVerifyCommand": (".SchemaVerifyCommand", "SchemaVerifyCommand"),
    "ServeCommand": (".ServeCommand", "ServeCommand"),
    "StorageLinkCommand": (".StorageLinkCommand", "StorageLinkCommand"),
    "ThreadSafeAMQPAckChannel": (
        ".ThreadSafeAMQPAckChannel",
        "ThreadSafeAMQPAckChannel",
    ),
    "TinkerCommand": (".TinkerCommand", "TinkerCommand"),
    "UpCommand": (".UpCommand", "UpCommand"),
    "VendorCommonsCommand": (".VendorCommonsCommand", "VendorCommonsCommand"),
    "Violation": (".Violation", "Violation"),
    "WARN": (".CheckResult", "WARN"),
    "audit_migrations": (".MigrationsCheckCommand", "audit_migrations"),
    "check_app_key_set": (".PreflightCommand", "check_app_key_set"),
    "check_debug_off_in_prod": (".PreflightCommand", "check_debug_off_in_prod"),
    "check_required_config_present": (
        ".PreflightCommand",
        "check_required_config_present",
    ),
    "fail": (".PreflightCommand", "fail"),
    "ok": (".PreflightCommand", "ok"),
    "parse_migration_file": (".MigrationsCheckCommand", "parse_migration_file"),
    "warn": (".PreflightCommand", "warn"),
}

__all__ = [
    "AMQPConnectionManager",
    "ActiveJobCancellationRegistry",
    "ArchBarrelsCommand",
    "ArchCheckCommand",
    "CacheClearCommand",
    "CheckResult",
    "DEFAULT_LOCK_TIMEOUT_MS",
    "DeliverySettlementError",
    "DevResetCommand",
    "DocsCommand",
    "DocsGenerateCommand",
    "DocsServeCommand",
    "DownCommand",
    "FAIL",
    "GenerateKeyCommand",
    "JobProcessor",
    "ListCommandsCommand",
    "MakeControllerCommand",
    "MakeEventCommand",
    "MakeJobCommand",
    "MakeListenerCommand",
    "MakeMailCommand",
    "MakeMiddlewareCommand",
    "MakeMigrationCommand",
    "MakeModelCommand",
    "MakeNotificationCommand",
    "MakePolicyCommand",
    "MigrateBaselineCommand",
    "MigrateCommand",
    "MigrateResetCommand",
    "MigrateRollbackCommand",
    "MigrateStatusCommand",
    "MigrationFile",
    "MigrationsCheckCommand",
    "ModelPruneCommand",
    "OK",
    "PreflightCommand",
    "QueueFlushCommand",
    "QueueHookCommand",
    "QueueHooksCommand",
    "QueueMonitorCommand",
    "QueuePurgeCommand",
    "QueueRelayCommand",
    "QueueRetryCommand",
    "QueueStatsCommand",
    "QueueWorkCommand",
    "RouteGeneratorCommand",
    "RouteListCommand",
    "ScheduleWorkCommand",
    "SchemaApplyCommand",
    "SchemaCheckCommand",
    "SchemaPlanCommand",
    "SchemaRollbackCommand",
    "SchemaVerifyCommand",
    "ServeCommand",
    "StorageLinkCommand",
    "ThreadSafeAMQPAckChannel",
    "TinkerCommand",
    "UpCommand",
    "VendorCommonsCommand",
    "Violation",
    "WARN",
    "audit_migrations",
    "check_app_key_set",
    "check_debug_off_in_prod",
    "check_required_config_present",
    "fail",
    "ok",
    "parse_migration_file",
    "warn",
]

_install_lazy_exports(__name__, _LAZY_EXPORTS)
