"""Generated route source rendering."""

from __future__ import annotations

import re
from pathlib import Path

from cara.support import paths


def _route_generate_route_artifacts(
    self,
    route_data: list[dict],
    route_type: str,
) -> dict[str, str]:
    """Return a bounded route aggregator plus any generated shards."""
    monolith = self._generate_routes_content_by_type(route_data, route_type)
    if len(monolith.splitlines()) <= self.MAX_ROUTE_SHARD_LINES:
        return {f"routes/{route_type}.py": monolith}

    groups = [
        group
        for controller_info in route_data
        for group in self._generate_controller_route_groups(controller_info)
    ]
    chunks = self._chunk_route_groups(groups)
    artifacts: dict[str, str] = {}
    shard_paths: list[str] = []
    for index, chunk in enumerate(chunks):
        path = f"routes/generated/{route_type}/group_{index:03d}.py"
        artifacts[path] = self._generate_route_shard_content(
            chunk,
            route_type=route_type,
        )
        shard_paths.append(path)
    artifacts[f"routes/{route_type}.py"] = self._generate_route_aggregator_content(
        route_data,
        route_type=route_type,
        shard_paths=shard_paths,
    )
    return artifacts


def _route_chunk_route_groups(self, groups: list[str]) -> list[list[str]]:
    """Partition complete route groups without splitting their semantics."""
    chunks: list[list[str]] = []
    current: list[str] = []
    current_lines = 7
    for group in groups:
        group_lines = len(group.splitlines()) + 1
        if current and current_lines + group_lines > self.MAX_ROUTE_SHARD_LINES:
            chunks.append(current)
            current = []
            current_lines = 7
        current.append(group)
        current_lines += group_lines
    if current:
        chunks.append(current)
    return chunks


def _route_generate_route_shard_content(
    groups: list[str],
    *,
    route_type: str,
) -> str:
    lines = [
        f'"""Auto-generated {route_type.upper()} route groups. Do not edit manually."""',
        "",
        "from cara.routing import Route",
        "",
        "",
        "def route_groups():",
        '    """Build this bounded shard\'s route groups."""',
        "    return (",
    ]
    for group in groups:
        lines.append(f"        {group},")
    lines.extend(("    )", ""))
    return "\n".join(lines)


def _route_generate_route_aggregator_content(
    self,
    route_data: list[dict],
    *,
    route_type: str,
    shard_paths: list[str],
) -> str:
    title = route_type.title()
    lines = [
        '"""',
        f"{title} Routes - Auto-generated by enhanced routes:generate command",
        "",
        f"This file contains all {route_type} routes parsed from controller docstrings.",
        "DO NOT EDIT MANUALLY - Use controller docstring annotations instead.",
        '"""',
        "",
        "from cara.routing import Route",
        "",
    ]
    lines.extend(self._generate_compiler_lines(route_data))
    if lines[-1] != "":
        lines.append("")

    loader_names: list[str] = []
    for index, shard_path in enumerate(shard_paths):
        loader = f"_route_groups_{index:03d}"
        module = "." + shard_path.removeprefix("routes/").removesuffix(".py").replace(
            "/", "."
        )
        lines.append(f"from {module} import route_groups as {loader}")
        loader_names.append(loader)

    lines.extend(("", "_ROUTE_GROUP_LOADERS = ("))
    lines.extend(f"    {loader}," for loader in loader_names)
    lines.extend((")", "", "", "def register_routes():"))
    lines.append(f'    """Register {route_type} routes from bounded generated shards."""')
    lines.append(
        "    groups = [group for loader in _ROUTE_GROUP_LOADERS for group in loader()]"
    )
    if route_type == "api":
        lines.append('    return Route.prefix("/api").routes(*groups)')
    else:
        lines.append("    return groups")
    lines.append("")
    return "\n".join(lines)


def _route_generate_compiler_lines(route_data: list[dict]) -> list[str]:
    lines = ["# Route Parameter Configuration"]
    for controller_info in route_data:
        for var_name, constraints in controller_info["compiler_vars"].items():
            rules = [rule.strip() for rule in constraints.split("|")]
            regex_rules = [
                rule
                for rule in rules
                if rule
                in {
                    "int",
                    "integer",
                    "string",
                    "alpha",
                    "alphanum",
                    "slug",
                    "uuid",
                    "bool",
                    "any",
                }
                or rule.startswith("regex:")
            ]
            validation_rules = [rule for rule in rules if rule not in regex_rules]
            if regex_rules:
                regex_pattern = regex_rules[0]
                if regex_pattern.startswith("regex:"):
                    lines.append(f'Route.compile("{var_name}", r"{regex_pattern[6:]}")')
                else:
                    lines.append(f'Route.compile("{var_name}", "{regex_pattern}")')
            if validation_rules:
                lines.append(
                    f'Route.validate("{var_name}", "{"|".join(validation_rules)}")'
                )
    return lines


def _route_remove_stale_route_shards(
    self,
    route_type: str,
    *,
    keep: set[str],
) -> None:
    """Delete only obsolete generator-owned shard files."""
    base = Path(paths("base"))
    shard_dir = base / "routes" / "generated" / route_type
    if not shard_dir.is_dir():
        return
    kept_paths = {base / path for path in keep}
    for path in shard_dir.glob("group_[0-9][0-9][0-9].py"):
        if path not in kept_paths:
            path.unlink()


def _route_filter_routes_by_type(
    self, route_data: list[dict], route_type: str
) -> list[dict]:
    """Filter routes by type (api, web, websocket)."""
    filtered_data = []

    for controller_info in route_data:
        filtered_controller = {
            "class_name": controller_info["class_name"],
            "file_path": controller_info["file_path"],
            "compiler_vars": controller_info["compiler_vars"],
            "route_groups": [],
            "global_middleware": controller_info["global_middleware"],
            "global_prefix": controller_info["global_prefix"],
        }

        # Filter route groups by type
        for group in controller_info["route_groups"]:
            group_type = group.get("type", "api")  # Default to api if not specified
            if group_type == route_type:
                filtered_controller["route_groups"].append(group)

        # Only include controller if it has routes of this type
        if filtered_controller["route_groups"]:
            filtered_data.append(filtered_controller)

    return filtered_data


def _route_generate_routes_content_by_type(
    self, route_data: list[dict], route_type: str
) -> str:
    """Generate routes content for specific type."""
    content_lines = []

    # Header
    route_type_title = route_type.title()
    header = [
        '"""',
        f"{route_type_title} Routes - Auto-generated by enhanced routes:generate command",
        "",
        f"This file contains all {route_type} routes parsed from controller docstrings.",
        "DO NOT EDIT MANUALLY - Use controller docstring annotations instead.",
        "",
        "Generated routes support:",
        "- Route groups with prefixes and middleware",
        "- Named routes and aliases",
        "- Parameter constraints and validation",
        "- Middleware (simple and parametered)",
        '"""',
        "",
        "from cara.routing import Route",
        "",
    ]

    content_lines.extend(header)

    # Generate route parameter validation and compilation
    content_lines.append("# Route Parameter Configuration")
    for controller_info in route_data:
        if controller_info["compiler_vars"]:
            for var_name, constraints in controller_info["compiler_vars"].items():
                # Same compiler logic as before
                rules = constraints.split("|")
                regex_rules = []
                validation_rules = []

                for rule in rules:
                    if rule.strip() in [
                        "int",
                        "integer",
                        "string",
                        "alpha",
                        "alphanum",
                        "slug",
                        "uuid",
                        "bool",
                        "any",
                    ] or rule.strip().startswith("regex:"):
                        regex_rules.append(rule.strip())
                    else:
                        validation_rules.append(rule.strip())

                if regex_rules:
                    regex_pattern = regex_rules[0]
                    if regex_pattern.startswith("regex:"):
                        pattern = regex_pattern[6:]
                        content_lines.append(f'Route.compile("{var_name}", r"{pattern}")')
                    else:
                        content_lines.append(
                            f'Route.compile("{var_name}", "{regex_pattern}")'
                        )

                if validation_rules:
                    validation_chain = "|".join(validation_rules)
                    content_lines.append(
                        f'Route.validate("{var_name}", "{validation_chain}")'
                    )

    content_lines.append("")

    # Generate register_routes function
    content_lines.append("def register_routes():")
    content_lines.append(f'    """Register {route_type} routes."""')

    if not route_data:
        content_lines.append("    return []")
    elif len(route_data) == 1:
        # Single controller - use same nested structure as multiple controllers
        controller_info = route_data[0]
        route_groups = self._generate_controller_route_groups(controller_info)
        if route_groups:
            if route_type == "api":
                content_lines.append('    return Route.prefix("/api").routes(')
                for group in route_groups:
                    content_lines.append(f"        {group}")
                content_lines.append("    )")
            else:
                # For websocket and web routes, return as list
                if len(route_groups) == 1:
                    content_lines.append(f"    return {route_groups[0]}")
                else:
                    content_lines.append("    return [")
                    for group in route_groups:
                        content_lines.append(f"        {group},")
                    content_lines.append("    ]")
        else:
            content_lines.append("    return []")
    else:
        # Multiple controllers
        if route_type == "api":
            content_lines.append('    return Route.prefix("/api").routes(')
            all_groups = []
            for controller_info in route_data:
                route_groups = self._generate_controller_route_groups(controller_info)
                all_groups.extend(route_groups)
            for group in all_groups:
                content_lines.append(f"        {group},")
            content_lines.append("    )")
        else:
            content_lines.append("    return [")
            for controller_info in route_data:
                route_groups = self._generate_controller_route_groups(controller_info)
                for group in route_groups:
                    content_lines.append(f"        {group},")
            content_lines.append("    ]")

    content_lines.append("")
    return "\n".join(content_lines)


def _route_generate_enhanced_routes_content(self, route_data: list[dict]) -> str:
    """Generate enhanced routes content with route groups."""
    content_lines = []

    # Header
    header = [
        '"""',
        "API Routes - Auto-generated by enhanced routes:generate command",
        "",
        "This file contains all application routes parsed from controller docstrings.",
        "DO NOT EDIT MANUALLY - Use controller docstring annotations instead.",
        "",
        "Generated routes support:",
        "- Route groups with prefixes and middleware",
        "- Named routes and aliases",
        "- Parameter constraints and validation",
        "- Middleware (simple and parametered)",
        '"""',
        "",
        "from cara.routing import Route",
        "",
    ]

    content_lines.extend(header)

    # Generate route parameter validation and compilation
    content_lines.append("# Route Parameter Configuration")
    for controller_info in route_data:
        if controller_info["compiler_vars"]:
            for var_name, constraints in controller_info["compiler_vars"].items():
                # Separate regex patterns from validation rules
                rules = constraints.split("|")
                regex_rules = []
                validation_rules = []

                for rule in rules:
                    if rule.strip() in [
                        "int",
                        "integer",
                        "string",
                        "alpha",
                        "alphanum",
                        "slug",
                        "uuid",
                        "bool",
                        "any",
                    ] or rule.strip().startswith("regex:"):
                        regex_rules.append(rule.strip())
                    else:
                        validation_rules.append(rule.strip())

                # Set regex pattern if any
                if regex_rules:
                    # Use the first regex rule for Route.compile
                    regex_pattern = regex_rules[0]
                    if regex_pattern.startswith("regex:"):
                        pattern = regex_pattern[6:]  # Remove "regex:" prefix
                        content_lines.append(f'Route.compile("{var_name}", r"{pattern}")')
                    else:
                        content_lines.append(
                            f'Route.compile("{var_name}", "{regex_pattern}")'
                        )

                # Set validation rules if any
                if validation_rules:
                    validation_chain = "|".join(validation_rules)
                    content_lines.append(
                        f'Route.validate("{var_name}", "{validation_chain}")'
                    )

    content_lines.append("")

    # Generate register_routes function
    content_lines.append("def register_routes():")
    content_lines.append('    """Register all application routes."""')

    if len(route_data) == 1:
        # Single controller - return the route group directly
        controller_info = route_data[0]
        route_groups = self._generate_controller_route_groups(controller_info)
        if route_groups:
            content_lines.append(f"    return {route_groups[0]}")
    else:
        # Multiple controllers - wrap in a common prefix
        content_lines.append('    return Route.prefix("/api").routes(')

        # Generate route groups for each controller
        all_groups = []
        for controller_info in route_data:
            route_groups = self._generate_controller_route_groups(controller_info)
            all_groups.extend(route_groups)

        for group in all_groups:
            content_lines.append(f"        {group},")

        content_lines.append("    )")

    content_lines.append("")

    return "\n".join(content_lines)


def _route_generate_controller_route_groups(self, controller_info: dict):
    """Generate route groups for a single controller."""
    class_name = controller_info["class_name"]
    route_groups = []

    for group in controller_info["route_groups"]:
        group_instance = self._generate_route_group(group, class_name)
        route_groups.append(group_instance)

    return route_groups


def _route_generate_route_group(self, group: dict, class_name: str):
    """Generate a single route group instance."""
    prefix = group["prefix"]
    middleware = group["middleware"]

    # Generate routes within the group
    group_routes = []
    for route in group["routes"]:
        route_methods = self._generate_route_methods_for_group(
            route, class_name, middleware or []
        )
        group_routes.extend(route_methods)

    # Build route group string
    group_parts = []
    if prefix:
        group_parts.append(f'Route.prefix("{prefix}")')

    if middleware:
        middleware_str = ", ".join(f'"{m}"' for m in middleware)
        if group_parts:
            group_parts.append(f".middleware([{middleware_str}])")
        else:
            # No prefix but group-level middleware: ``Route.middleware``
            # is an INSTANCE method (chaining helper), not a classmethod,
            # so ``Route.middleware([...])`` raises TypeError at import.
            # Emit an empty-prefix ``RouteGroup`` instead — it applies
            # the middleware and (empty prefix) leaves the URL untouched.
            group_parts.append(f'Route.prefix("").middleware([{middleware_str}])')

    if not group_parts:
        group_parts.append("Route")

    # Add routes using Cara's syntax - pass routes as individual arguments, not a list
    routes_str = ",\n            ".join(group_routes)
    group_str = "".join(group_parts) + f".routes(\n            {routes_str}\n        )"

    return group_str


def _route_generate_route_methods_for_group(
    self,
    route: dict,
    class_name: str,
    group_middleware: list[str],
):
    """Generate HTTP/WebSocket methods for a route within a group."""
    return [self._build_route_instance(method, class_name) for method in route["methods"]]


def _route_build_route_instance(self, method: dict, class_name: str) -> str:
    """Build a single Route instance string."""
    http_method = method["http_method"].lower()
    controller_method = method["controller_method"]
    route_path = self._normalize_route_path(method.get("path", ""))

    # Build route parameters
    params = self._build_route_params(
        path=route_path,
        controller=f"{class_name}@{controller_method}",
        name=method.get("as"),
        middleware=method.get("middleware", []),
    )

    # Generate route instance
    params_str = ", ".join(params)
    route_method = "ws" if http_method == "ws" else http_method

    return f"Route.{route_method}({params_str})"


def _route_normalize_route_path(self, path: str) -> str:
    """Convert {param} to @param format for Cara routing."""
    if not path:
        return ""
    return re.sub(r"\{(\w+)\}", r"@\1", path)


def _route_build_route_params(
    self,
    path: str,
    controller: str,
    name: str | None = None,
    middleware: list[str] | None = None,
) -> list[str]:
    """Build route parameters list."""
    params = [f'"{path}"', f'"{controller}"']

    # Add optional middleware
    if middleware:
        middleware_str = ", ".join(f'"{m}"' for m in middleware)
        params.append(f"middleware=[{middleware_str}]")

    # Add optional route name
    if name:
        params.append(f'name="{name}"')

    return params
