"""
Mail Generation Command for the Cara framework.
"""

from pathlib import Path

from cara.commands import CommandBase
from cara.decorators import command
from cara.support import paths


@command(
    name="make:mail",
    help="Generate a new Mail class with enhanced options.",
    options={
        "--dry": "Show what would be generated without creating files",
        "--force": "Overwrite existing mail file",
        "--markdown": "Generate a markdown-based mail template",
    },
)
class MakeMailCommand(CommandBase):
    """Generate Mail classes with enhanced configuration."""

    def handle(self, name: str):
        """Handle mail generation."""
        self.info("🏗️  Mail Generation")

        try:
            mail_info = self._prepare_mail_info(name)
        except ValueError as e:
            self.error(f"❌ {e}")
            return

        if self._check_existing_file(mail_info):
            return

        if self.option("dry"):
            self._show_dry_run(mail_info)
            return

        try:
            self._generate_mail(mail_info)
        except Exception as e:
            self.error(f"❌ Failed to generate mail: {e}")

    def _prepare_mail_info(self, name: str) -> dict:
        """Prepare mail information."""
        if not name:
            raise ValueError("Mail name is required")

        class_name = self._clean_class_name(name)
        template_name = self._generate_template_name(class_name)

        mail_dir = Path(paths("mailables"))  # Using proper path helper
        file_path = mail_dir / f"{class_name}.py"

        return {
            "class_name": class_name,
            "template_name": template_name,
            "file_path": file_path,
            "mail_dir": mail_dir,
            "is_markdown": self.option("markdown"),
        }

    def _clean_class_name(self, name: str) -> str:
        """Clean and format class name."""
        if name.endswith(".py"):
            name = name[:-3]
        name = "".join(word.capitalize() for word in name.replace("_", " ").split())
        if not name.endswith("Mail"):
            name += "Mail"
        return name

    def _generate_template_name(self, class_name: str) -> str:
        """Generate template name from class name."""
        name = class_name.replace("Mail", "")
        result = ""
        for i, char in enumerate(name):
            if char.isupper() and i > 0:
                result += "_"
            result += char.lower()
        return result

    def _check_existing_file(self, mail_info: dict) -> bool:
        """Check if mail file already exists."""
        if mail_info["file_path"].exists() and not self.option("force"):
            self.warning(f"⚠️  Mail already exists: {mail_info['file_path']}")
            self.info("💡 Use --force to overwrite existing mail")
            return True
        return False

    def _show_dry_run(self, mail_info: dict) -> None:
        """Show dry run preview."""
        self.info("🔍 DRY RUN MODE - No files will be created")
        self.info("📋 Mail configuration:")
        self.info(f"   Class Name: {mail_info['class_name']}")
        self.info(f"   Template: {mail_info['template_name']}")
        self.info(f"   File Path: {mail_info['file_path']}")
        self.info(f"   Type: {'Markdown' if mail_info['is_markdown'] else 'HTML'}")

    def _generate_mail(self, mail_info: dict) -> None:
        """Generate the mail file."""
        self.info("🔧 Configuration:")
        self.info(f"   Class: {mail_info['class_name']}")
        self.info(f"   Template: {mail_info['template_name']}")
        self.info(f"   File: {mail_info['file_path']}")
        self.info(f"   Type: {'Markdown' if mail_info['is_markdown'] else 'HTML'}")

        mail_info["mail_dir"].mkdir(parents=True, exist_ok=True)
        code = self._generate_mail_code(mail_info)

        self.info("⚡ Generating mail...")
        try:
            with open(mail_info["file_path"], "w", encoding="utf-8") as f:
                f.write(code)

            self.info("✅ Mail created successfully!")
            self.info(f"📁 Location: {mail_info['file_path']}")
            self._show_usage_tips(mail_info)

        except Exception as e:
            raise Exception(f"Failed to write mail file: {e}")

    def _generate_mail_code(self, mail_info: dict) -> str:
        """Generate the mail class code."""
        stub_path = Path(paths("cara")) / "commands" / "stubs" / "Mail.stub"

        with open(stub_path, "r", encoding="utf-8") as f:
            stub_content = f.read()

        code = stub_content.replace("{{ class_name }}", mail_info["class_name"])
        code = code.replace("{{ template_name }}", mail_info["template_name"])
        code = code.replace(
            "{{ docstring }}",
            f"{mail_info['class_name']}\n\nGenerated by Cara framework make:mail command.",
        )

        return code

    def _show_usage_tips(self, mail_info: dict) -> None:
        """Show usage examples."""
        class_name = mail_info["class_name"]
        template_name = mail_info["template_name"]

        self.info("\n💡 Usage Tips:")
        self.info(f"   Import: from app.mail import {class_name}")
        self.info("   Send mail:")
        self.info(f"     Mail.send({class_name}())")
        self.info("   Queue mail:")
        self.info(f"     Mail.queue({class_name}())")

        template_type = "md" if mail_info["is_markdown"] else "html"
        self.info("\n📧 Remember to create mail template:")
        self.info(f"   resources/templates/mail/{template_name}.{template_type}")
