"""
JobLog Generation Command for the Cara framework.

This module provides a CLI command to generate JobLog model for advanced job tracking.
"""

from pathlib import Path

from cara.commands import CommandBase
from cara.decorators import command
from cara.support import paths


@command(
    name="make:job-log",
    help="Generate a JobLog model for advanced job tracking",
    options={
        "--dry": "Show what would be generated without creating files",
        "--force": "Overwrite existing model file",
        "--table": "Specify table name (default: job_logs)",
    },
)
class MakeJobLogCommand(CommandBase):
    """Generate JobLog model for advanced job tracking."""

    def handle(self, name: str = "JobLog"):
        """Handle JobLog generation."""
        self.info("🏗️  JobLog Generation")

        # Validate and prepare
        try:
            joblog_info = self._prepare_joblog_info(name)
        except ValueError as e:
            self.error(f"❌ {e}")
            return

        # Check if file exists
        if self._check_existing_file(joblog_info):
            return

        # Dry run mode
        if self.option("dry"):
            self._show_dry_run(joblog_info)
            return

        # Generate JobLog
        try:
            self._generate_joblog(joblog_info)
        except Exception as e:
            self.error(f"❌ Failed to generate JobLog: {e}")
            raise

    def _prepare_joblog_info(self, name: str) -> dict:
        """Prepare JobLog generation information."""
        if not name:
            raise ValueError("JobLog name cannot be empty")

        # Clean name
        class_name = name.replace("JobLog", "").strip()
        if not class_name:
            class_name = "JobLog"
        else:
            class_name = f"{class_name}JobLog" if not class_name.endswith("JobLog") else class_name

        # Determine paths
        models_dir = Path(paths("app")) / "models"
        file_path = models_dir / f"{class_name}.py"
        
        # Table name
        table_name = self.option("table") or "job_logs"

        return {
            "class_name": class_name,
            "table_name": table_name,
            "models_dir": models_dir,
            "file_path": file_path,
        }

    def _check_existing_file(self, joblog_info: dict) -> bool:
        """Check if JobLog file already exists."""
        if joblog_info["file_path"].exists() and not self.option("force"):
            self.error(f"❌ JobLog already exists: {joblog_info['file_path']}")
            self.info("💡 Use --force to overwrite or choose a different name")
            return True
        return False

    def _show_dry_run(self, joblog_info: dict) -> None:
        """Show what would be generated in dry run mode."""
        self.info("🔍 Dry Run - JobLog Generation Preview:")
        self.info(f"   Class: {joblog_info['class_name']}")
        self.info(f"   Table: {joblog_info['table_name']}")
        self.info(f"   File: {joblog_info['file_path']}")
        self.info("   Features: Job tracking, retry logic, analytics")

    def _generate_joblog(self, joblog_info: dict) -> None:
        """Generate the JobLog model."""
        # Create directory
        joblog_info["models_dir"].mkdir(parents=True, exist_ok=True)

        # Generate code
        code = self._generate_joblog_code(joblog_info)

        # Write file
        self.info("⚡ Generating JobLog model...")

        try:
            with open(joblog_info["file_path"], "w", encoding="utf-8") as f:
                f.write(code)

            self.info("✅ JobLog model created successfully!")
            self.info(f"📁 Location: {joblog_info['file_path']}")

            self._show_usage_tips(joblog_info)

        except Exception as e:
            raise Exception(f"Failed to write JobLog file: {e}")

    def _generate_joblog_code(self, joblog_info: dict) -> str:
        """Generate the JobLog model code using stub."""
        class_name = joblog_info["class_name"]
        table_name = joblog_info["table_name"]

        # Load stub file
        stub_path = Path(paths("cara")) / "commands" / "stubs" / "JobLog.stub"

        with open(stub_path, "r", encoding="utf-8") as f:
            stub_content = f.read()

        # Replace placeholders
        code = stub_content.replace("{{ class_name }}", class_name)
        code = code.replace("{{ table_name }}", table_name)
        code = code.replace(
            "{{ docstring }}",
            f"{class_name} Model for Advanced Job Tracking.\n\nGenerated by Cara framework make:job-log command.",
        )

        return code

    def _show_usage_tips(self, joblog_info: dict) -> None:
        """Show usage examples for the generated JobLog."""
        class_name = joblog_info["class_name"]

        self.info("\n💡 Usage Tips:")
        self.info(f"   Import: from app.models import {class_name}")
        self.info("   Use with Trackable trait in jobs:")
        self.info("     from cara.queues.tracking import Trackable")
        self.info("     class MyJob(Trackable, Queueable, ShouldQueue): ...")
        self.info("")
        self.info("📋 Next Steps:")
        self.info("1. Run: python craft make:migration  # Auto-generate migration")
        self.info("2. Run: python craft migrate         # Create tables")
        self.info("3. Add JobLog to app/models/__init__.py exports")
        self.info("4. Use Trackable trait in your job classes") 