"""
Listener Generation Command for the Cara framework.
"""

from pathlib import Path

from cara.commands import CommandBase
from cara.decorators import command
from cara.support import paths


@command(
    name="make:listener",
    help="Generate a new Listener class with enhanced options.",
    options={
        "--dry": "Show what would be generated without creating files",
        "--force": "Overwrite existing listener file",
        "--event=?": "The event class this listener should handle",
    },
)
class MakeListenerCommand(CommandBase):
    """Generate Listener classes with enhanced configuration."""

    def handle(self, name: str, event: str = None):
        """Handle listener generation."""
        self.info("🏗️  Listener Generation")

        try:
            listener_info = self._prepare_listener_info(name, event)
        except ValueError as e:
            self.error(f"❌ {e}")
            return

        if self._check_existing_file(listener_info):
            return

        if self.option("dry"):
            self._show_dry_run(listener_info)
            return

        try:
            self._generate_listener(listener_info)
        except Exception as e:
            self.error(f"❌ Failed to generate listener: {e}")

    def _prepare_listener_info(self, name: str, event: str = None) -> dict:
        """Prepare listener information."""
        if not name:
            raise ValueError("Listener name is required")

        class_name = self._clean_class_name(name)

        listeners_dir = Path(paths("listeners"))
        file_path = listeners_dir / f"{class_name}.py"

        return {
            "class_name": class_name,
            "event_class": event,
            "file_path": file_path,
            "listeners_dir": listeners_dir,
        }

    def _clean_class_name(self, name: str) -> str:
        """Clean and format class name."""
        if name.endswith(".py"):
            name = name[:-3]

        # Convert to PascalCase preserving existing capitalization
        if "_" in name or " " in name:
            return "".join(word.capitalize() for word in name.replace("_", " ").split())
        else:
            return name[0].upper() + name[1:] if name else ""

    def _check_existing_file(self, listener_info: dict) -> bool:
        """Check if listener file already exists."""
        if listener_info["file_path"].exists() and not self.option("force"):
            self.warning(f"⚠️  Listener already exists: {listener_info['file_path']}")
            self.info("💡 Use --force to overwrite existing listener")
            return True
        return False

    def _show_dry_run(self, listener_info: dict) -> None:
        """Show dry run preview."""
        self.info("🔍 DRY RUN MODE - No files will be created")
        self.info("📋 Listener configuration:")
        self.info(f"   Class Name: {listener_info['class_name']}")
        self.info(f"   Event Class: {listener_info['event_class'] or 'Generic'}")
        self.info(f"   File Path: {listener_info['file_path']}")

    def _generate_listener(self, listener_info: dict) -> None:
        """Generate the listener file."""
        self.info("🔧 Configuration:")
        self.info(f"   Class: {listener_info['class_name']}")
        self.info(f"   Event: {listener_info['event_class'] or 'Generic'}")
        self.info(f"   File: {listener_info['file_path']}")

        listener_info["listeners_dir"].mkdir(parents=True, exist_ok=True)
        code = self._generate_listener_code(listener_info)

        self.info("⚡ Generating listener...")
        try:
            with open(listener_info["file_path"], "w", encoding="utf-8") as f:
                f.write(code)

            self.info("✅ Listener created successfully!")
            self.info(f"📁 Location: {listener_info['file_path']}")
            self._show_usage_tips(listener_info)

        except Exception as e:
            raise Exception(f"Failed to write listener file: {e}")

    def _generate_listener_code(self, listener_info: dict) -> str:
        """Generate the listener class code."""
        stub_path = Path(paths("cara")) / "commands" / "stubs" / "Listener.stub"

        with open(stub_path, "r", encoding="utf-8") as f:
            stub_content = f.read()

        code = stub_content.replace("{{ class_name }}", listener_info["class_name"])
        code = code.replace(
            "{{ docstring }}",
            f"{listener_info['class_name']}\n\nGenerated by Cara framework make:listener command.",
        )

        return code

    def _show_usage_tips(self, listener_info: dict) -> None:
        """Show usage examples."""
        class_name = listener_info["class_name"]

        self.info("\n💡 Usage Tips:")
        self.info(f"   Import: from app.listeners import {class_name}")
        self.info("   Register listener:")
        self.info(f"     Event.listen('event.name', {class_name})")
        if listener_info["event_class"]:
            self.info(f"   For {listener_info['event_class']} events:")
            self.info(
                f"     Event.listen('{listener_info['event_class'].lower()}', {class_name})"
            )
