"""
Event Generation Command for the Cara framework.
"""

from pathlib import Path

from cara.commands import CommandBase
from cara.decorators import command
from cara.support import paths


@command(
    name="make:event",
    help="Generate a new Event class with enhanced options.",
    options={
        "--dry": "Show what would be generated without creating files",
        "--force": "Overwrite existing event file",
    },
)
class MakeEventCommand(CommandBase):
    """Generate Event classes with enhanced configuration."""

    def handle(self, name: str):
        """Handle event generation."""
        self.info("🏗️  Event Generation")

        try:
            event_info = self._prepare_event_info(name)
        except ValueError as e:
            self.error(f"❌ {e}")
            return

        if self._check_existing_file(event_info):
            return

        if self.option("dry"):
            self._show_dry_run(event_info)
            return

        try:
            self._generate_event(event_info)
        except Exception as e:
            self.error(f"❌ Failed to generate event: {e}")

    def _prepare_event_info(self, name: str) -> dict:
        """Prepare event information."""
        if not name:
            raise ValueError("Event name is required")

        class_name = self._clean_class_name(name)
        event_name = self._generate_event_name(class_name)

        events_dir = Path(paths("events"))  # Using proper path helper
        file_path = events_dir / f"{class_name}.py"

        return {
            "class_name": class_name,
            "event_name": event_name,
            "file_path": file_path,
            "events_dir": events_dir,
        }

    def _clean_class_name(self, name: str) -> str:
        """Clean and format class name."""
        if name.endswith(".py"):
            name = name[:-3]

        # Convert to PascalCase preserving existing capitalization
        if "_" in name or " " in name:
            # Split on underscores and spaces, then capitalize each word
            return "".join(word.capitalize() for word in name.replace("_", " ").split())
        else:
            # Preserve existing PascalCase
            return name[0].upper() + name[1:] if name else ""

    def _generate_event_name(self, class_name: str) -> str:
        """Generate event name from class name."""
        # Convert PascalCase to snake_case
        result = ""
        for i, char in enumerate(class_name):
            if char.isupper() and i > 0:
                result += "."
            result += char.lower()
        return result

    def _check_existing_file(self, event_info: dict) -> bool:
        """Check if event file already exists."""
        if event_info["file_path"].exists() and not self.option("force"):
            self.warning(f"⚠️  Event already exists: {event_info['file_path']}")
            self.info("💡 Use --force to overwrite existing event")
            return True
        return False

    def _show_dry_run(self, event_info: dict) -> None:
        """Show dry run preview."""
        self.info("🔍 DRY RUN MODE - No files will be created")
        self.info("📋 Event configuration:")
        self.info(f"   Class Name: {event_info['class_name']}")
        self.info(f"   Event Name: {event_info['event_name']}")
        self.info(f"   File Path: {event_info['file_path']}")

    def _generate_event(self, event_info: dict) -> None:
        """Generate the event file."""
        self.info("🔧 Configuration:")
        self.info(f"   Class: {event_info['class_name']}")
        self.info(f"   Event: {event_info['event_name']}")
        self.info(f"   File: {event_info['file_path']}")

        event_info["events_dir"].mkdir(parents=True, exist_ok=True)
        code = self._generate_event_code(event_info)

        self.info("⚡ Generating event...")
        try:
            with open(event_info["file_path"], "w", encoding="utf-8") as f:
                f.write(code)

            self.info("✅ Event created successfully!")
            self.info(f"📁 Location: {event_info['file_path']}")
            self._show_usage_tips(event_info)

        except Exception as e:
            raise Exception(f"Failed to write event file: {e}")

    def _generate_event_code(self, event_info: dict) -> str:
        """Generate the event class code."""
        stub_path = Path(paths("cara")) / "commands" / "stubs" / "Event.stub"

        with open(stub_path, "r", encoding="utf-8") as f:
            stub_content = f.read()

        code = stub_content.replace("{{ class_name }}", event_info["class_name"])
        code = code.replace("{{ event_name }}", event_info["event_name"])
        code = code.replace(
            "{{ docstring }}",
            f"{event_info['class_name']}\n\nGenerated by Cara framework make:event command.",
        )

        return code

    def _show_usage_tips(self, event_info: dict) -> None:
        """Show usage examples."""
        class_name = event_info["class_name"]
        event_name = event_info["event_name"]

        self.info("\n💡 Usage Tips:")
        self.info(f"   Import: from app.events import {class_name}")
        self.info("   Fire the event:")
        self.info("     from cara.facades import Event")
        self.info(f"     Event.fire('{event_name}', data)")
        self.info("   Or create instance:")
        self.info(f"     event = {class_name}()")
        self.info("     Event.fire(event)")

        self.info("\n   Generate a listener:")
        self.info(
            f"     python craft make:listener Handle{class_name} --event={class_name}"
        )

        self.info("\n   Register in event service provider:")
        self.info(f"     {class_name} -> [Handle{class_name}]")
