"""Dependency-bounded public ORM surface."""

from cara._LazyExports import _install_lazy_exports

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "AggregateExpression": (".expressions", "AggregateExpression"),
    "ArrayCast": (".casts", "ArrayCast"),
    "Atomic": (".Atomic", "Atomic"),
    "BaseCast": (".casts", "BaseCast"),
    "BaseConnection": (".connections", "BaseConnection"),
    "BaseGrammar": (".query", "BaseGrammar"),
    "BasePaginator": (".pagination", "BasePaginator"),
    "BaseRelationship": (".relationships", "BaseRelationship"),
    "BaseScope": (".scopes", "BaseScope"),
    "BelongsTo": (".relationships", "BelongsTo"),
    "BetweenExpression": (".expressions", "BetweenExpression"),
    "Blueprint": (".schema", "Blueprint"),
    "BlueprintExecutor": (".schema", "BlueprintExecutor"),
    "BoolCast": (".casts", "BoolCast"),
    "CONNECTION_POOL": (".connections", "CONNECTION_POOL"),
    "CONSTRAINT_BUILDERS": (".schema", "CONSTRAINT_BUILDERS"),
    "CastRegistry": (".casts", "CastRegistry"),
    "CollectionCast": (".casts", "CollectionCast"),
    "Column": (".schema", "Column"),
    "ColumnFactory": (".schema", "ColumnFactory"),
    "ConfigurationNotFound": (".ConfigurationNotFound", "ConfigurationNotFound"),
    "ConnectionFactory": (".connections", "ConnectionFactory"),
    "ConnectionResolver": (".connections", "ConnectionResolver"),
    "Constraint": (".schema", "Constraint"),
    "ConstraintManager": (".schema", "ConstraintManager"),
    "CursorPaginator": (".pagination", "CursorPaginator"),
    "DatabaseManager": (".DatabaseManager", "DatabaseManager"),
    "DateCast": (".casts", "DateCast"),
    "DateManager": (".utils", "DateManager"),
    "DateTimeCast": (".casts", "DateTimeCast"),
    "DecimalCast": (".casts", "DecimalCast"),
    "EagerRelations": (".query", "EagerRelations"),
    "EloquentProvider": (".EloquentProvider", "EloquentProvider"),
    "EmailCast": (".casts", "EmailCast"),
    "EncryptedCast": (".casts", "EncryptedCast"),
    "EncryptedJsonCast": (".casts", "EncryptedJsonCast"),
    "EnhancedCastRegistry": (".casts", "EnhancedCastRegistry"),
    "F": (".expressions", "F"),
    "FIELD_TYPES_WITHOUT_NAMES": (".schema", "FIELD_TYPES_WITHOUT_NAMES"),
    "FIELD_TYPES_WITH_NAMES": (".schema", "FIELD_TYPES_WITH_NAMES"),
    "Factory": (".factories", "Factory"),
    "Field": (".schema", "Field"),
    "FieldBuilder": (".schema", "FieldBuilder"),
    "FieldDefinition": (".schema", "FieldDefinition"),
    "FieldDiff": (".migrations", "FieldDiff"),
    "FieldMeta": (".schema", "FieldMeta"),
    "FieldProxy": (".schema", "FieldProxy"),
    "FloatCast": (".casts", "FloatCast"),
    "ForeignKeyBuilder": (".schema", "ForeignKeyBuilder"),
    "ForeignKeyConstraint": (".schema", "ForeignKeyConstraint"),
    "FromTable": (".expressions", "FromTable"),
    "Greatest": (".expressions", "Greatest"),
    "GroupByExpression": (".expressions", "GroupByExpression"),
    "HasAttributes": (".concerns", "HasAttributes"),
    "HasMany": (".relationships", "HasMany"),
    "HasOne": (".relationships", "HasOne"),
    "HasRelationships": (".concerns", "HasRelationships"),
    "HasTimestamps": (".concerns", "HasTimestamps"),
    "HashCast": (".casts", "HashCast"),
    "HavingExpression": (".expressions", "HavingExpression"),
    "Index": (".schema", "Index"),
    "IntCast": (".casts", "IntCast"),
    "JoinClause": (".expressions", "JoinClause"),
    "JsonCast": (".casts", "JsonCast"),
    "Least": (".expressions", "Least"),
    "LengthAwarePaginator": (".pagination", "LengthAwarePaginator"),
    "MakesPrunable": (".concerns", "MakesPrunable"),
    "MakesPublicId": (".concerns", "MakesPublicId"),
    "MakesSoftDeletes": (".scopes", "MakesSoftDeletes"),
    "MakesTenantScope": (".scopes", "MakesTenantScope"),
    "MakesTimestamps": (".scopes", "MakesTimestamps"),
    "Migration": (".migrations", "Migration"),
    "MigrationColumn": (".migrations", "MigrationColumn"),
    "MigrationExecutor": (".migrations", "MigrationExecutor"),
    "MigrationFileManager": (".migrations", "MigrationFileManager"),
    "MigrationGenerator": (".migrations", "MigrationGenerator"),
    "MigrationModel": (".models", "MigrationModel"),
    "MigrationTracker": (".migrations", "MigrationTracker"),
    "Model": (".models", "Model"),
    "ModelDiscoverer": (".migrations", "ModelDiscoverer"),
    "ModelMeta": (".models", "ModelMeta"),
    "ModelMigrationComparator": (".migrations", "ModelMigrationComparator"),
    "ORDER_BY_COLUMN_RE": (".query", "ORDER_BY_COLUMN_RE"),
    "ObservesEvents": (".observers", "ObservesEvents"),
    "OnClause": (".expressions", "OnClause"),
    "OnValueClause": (".expressions", "OnValueClause"),
    "Operation": (".expressions", "Operation"),
    "OrderByExpression": (".expressions", "OrderByExpression"),
    "PhoneCast": (".casts", "PhoneCast"),
    "Pivot": (".models", "Pivot"),
    "Platform": (".schema", "Platform"),
    "PostgresConnection": (".connections", "PostgresConnection"),
    "PostgresGrammar": (".query", "PostgresGrammar"),
    "PostgresPlatform": (".schema", "PostgresPlatform"),
    "PostgresPostProcessor": (".query", "PostgresPostProcessor"),
    "QueryBuilder": (".query", "QueryBuilder"),
    "QueryExpression": (".expressions", "QueryExpression"),
    "Raw": (".expressions", "Raw"),
    "SQLiteConnection": (".connections", "SQLiteConnection"),
    "SQLiteGrammar": (".query", "SQLiteGrammar"),
    "SQLitePlatform": (".schema", "SQLitePlatform"),
    "SQLitePostProcessor": (".query", "SQLitePostProcessor"),
    "Schema": (".schema", "Schema"),
    "SchemaConnectionManager": (".schema", "SchemaConnectionManager"),
    "SchemaQueryExecutor": (".schema", "SchemaQueryExecutor"),
    "SelectExpression": (".expressions", "SelectExpression"),
    "SimplePaginator": (".pagination", "SimplePaginator"),
    "SlugCast": (".casts", "SlugCast"),
    "SoftDeleteScope": (".scopes", "SoftDeleteScope"),
    "SubGroupExpression": (".expressions", "SubGroupExpression"),
    "SubSelectExpression": (".expressions", "SubSelectExpression"),
    "Table": (".schema", "Table"),
    "TableDiff": (".schema", "TableDiff"),
    "TenantScope": (".scopes", "TenantScope"),
    "TimeCast": (".casts", "TimeCast"),
    "TimeStampsScope": (".scopes", "TimeStampsScope"),
    "TimestampCast": (".casts", "TimestampCast"),
    "TokenCast": (".casts", "TokenCast"),
    "TransactionContext": (".query", "TransactionContext"),
    "URLCast": (".casts", "URLCast"),
    "UUIDCast": (".casts", "UUIDCast"),
    "UpdateQueryExpression": (".expressions", "UpdateQueryExpression"),
    "_MULTI_SPACE_RE": (".query", "_MULTI_SPACE_RE"),
    "atomic": (".Atomic", "atomic"),
    "belongs_to": (".relationships", "belongs_to"),
    "cast_value": (".casts", "cast_value"),
    "get_cast_instance": (".casts", "get_cast_instance"),
    "has_many": (".relationships", "has_many"),
    "has_one": (".relationships", "has_one"),
    "is_unique_violation": (".Integrity", "is_unique_violation"),
    "keyset_operator": (".pagination", "keyset_operator"),
    "keyset_predicate": (".pagination", "keyset_predicate"),
    "migration_table_actions": (".migrations", "migration_table_actions"),
    "regexp": (".connections", "regexp"),
    "register_cast": (".casts", "register_cast"),
    "reset_registry": (".connections", "reset_registry"),
    "sqlstate_of": (".Integrity", "sqlstate_of"),
    "summarize_change_name": (".migrations", "summarize_change_name"),
}

__all__ = [
    "AggregateExpression",
    "ArrayCast",
    "Atomic",
    "BaseCast",
    "BaseConnection",
    "BaseGrammar",
    "BasePaginator",
    "BaseRelationship",
    "BaseScope",
    "BelongsTo",
    "BetweenExpression",
    "Blueprint",
    "BlueprintExecutor",
    "BoolCast",
    "CONNECTION_POOL",
    "CONSTRAINT_BUILDERS",
    "CastRegistry",
    "CollectionCast",
    "Column",
    "ColumnFactory",
    "ConfigurationNotFound",
    "ConnectionFactory",
    "ConnectionResolver",
    "Constraint",
    "ConstraintManager",
    "CursorPaginator",
    "DatabaseManager",
    "DateCast",
    "DateManager",
    "DateTimeCast",
    "DecimalCast",
    "EagerRelations",
    "EloquentProvider",
    "EmailCast",
    "EncryptedCast",
    "EncryptedJsonCast",
    "EnhancedCastRegistry",
    "F",
    "FIELD_TYPES_WITHOUT_NAMES",
    "FIELD_TYPES_WITH_NAMES",
    "Factory",
    "Field",
    "FieldBuilder",
    "FieldDefinition",
    "FieldDiff",
    "FieldMeta",
    "FieldProxy",
    "FloatCast",
    "ForeignKeyBuilder",
    "ForeignKeyConstraint",
    "FromTable",
    "Greatest",
    "GroupByExpression",
    "HasAttributes",
    "HasMany",
    "HasOne",
    "HasRelationships",
    "HasTimestamps",
    "HashCast",
    "HavingExpression",
    "Index",
    "IntCast",
    "JoinClause",
    "JsonCast",
    "Least",
    "LengthAwarePaginator",
    "MakesPrunable",
    "MakesPublicId",
    "MakesSoftDeletes",
    "MakesTenantScope",
    "MakesTimestamps",
    "Migration",
    "MigrationColumn",
    "MigrationExecutor",
    "MigrationFileManager",
    "MigrationGenerator",
    "MigrationModel",
    "MigrationTracker",
    "Model",
    "ModelDiscoverer",
    "ModelMeta",
    "ModelMigrationComparator",
    "ORDER_BY_COLUMN_RE",
    "ObservesEvents",
    "OnClause",
    "OnValueClause",
    "Operation",
    "OrderByExpression",
    "PhoneCast",
    "Pivot",
    "Platform",
    "PostgresConnection",
    "PostgresGrammar",
    "PostgresPlatform",
    "PostgresPostProcessor",
    "QueryBuilder",
    "QueryExpression",
    "Raw",
    "SQLiteConnection",
    "SQLiteGrammar",
    "SQLitePlatform",
    "SQLitePostProcessor",
    "Schema",
    "SchemaConnectionManager",
    "SchemaQueryExecutor",
    "SelectExpression",
    "SimplePaginator",
    "SlugCast",
    "SoftDeleteScope",
    "SubGroupExpression",
    "SubSelectExpression",
    "Table",
    "TableDiff",
    "TenantScope",
    "TimeCast",
    "TimeStampsScope",
    "TimestampCast",
    "TokenCast",
    "TransactionContext",
    "URLCast",
    "UUIDCast",
    "UpdateQueryExpression",
    "_MULTI_SPACE_RE",
    "atomic",
    "belongs_to",
    "cast_value",
    "get_cast_instance",
    "has_many",
    "has_one",
    "is_unique_violation",
    "keyset_operator",
    "keyset_predicate",
    "migration_table_actions",
    "regexp",
    "register_cast",
    "reset_registry",
    "sqlstate_of",
    "summarize_change_name",
]

_install_lazy_exports(__name__, _LAZY_EXPORTS)
