"""Observability bootstrap — generic wiring for tracking backends.

Currently ships Sentry / GlitchTip. Future backends (OpenTelemetry,
Datadog) plug into the same ``setup_observability`` family.
"""

from cara._LazyExports import _install_lazy_exports

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "AlertSink": (".AlertSink", "AlertSink"),
    "MetricsBase": (".MetricsBase", "MetricsBase"),
    "REGISTRY": (".MetricsBase", "REGISTRY"),
    "available": (".Trace", "available"),
    "bool_label": (".MetricsBase", "bool_label"),
    "clear_scope": (".Sentry", "clear_scope"),
    "counter": (".MetricsBase", "counter"),
    "current_span_id": (".Trace", "current_span_id"),
    "current_trace_id": (".Trace", "current_trace_id"),
    "emit": (".WideEvent", "emit"),
    "enabled": (".WideEvent", "enabled"),
    "extracted_context": (".Trace", "extracted_context"),
    "gauge": (".MetricsBase", "gauge"),
    "get_tracer": (".Trace", "get_tracer"),
    "histogram": (".MetricsBase", "histogram"),
    "histogram_buckets_long": (".MetricsBase", "histogram_buckets_long"),
    "histogram_buckets_short": (".MetricsBase", "histogram_buckets_short"),
    "init_build_info": (".MetricsBase", "init_build_info"),
    "inject": (".Trace", "inject"),
    "metric_name": (".MetricsBase", "metric_name"),
    "normalize_metric_path": (".MetricsBase", "normalize_metric_path"),
    "parent_span_id_from_carrier": (".Trace", "parent_span_id_from_carrier"),
    "record_exception": (".Trace", "record_exception"),
    "render": (".MetricsBase", "render"),
    "root_span": (".Trace", "root_span"),
    "sample_db_pool_metrics": (".MetricsBase", "sample_db_pool_metrics"),
    "set_attributes": (".Trace", "set_attributes"),
    "set_request_tag": (".Sentry", "set_request_tag"),
    "set_request_user": (".Sentry", "set_request_user"),
    "setup_sentry": (".Sentry", "setup_sentry"),
    "setup_tracing": (".Tracing", "setup_tracing"),
    "span": (".Trace", "span"),
    "start_http_server": (".MetricsBase", "start_http_server"),
    "status_class": (".MetricsBase", "status_class"),
}

__all__ = [
    "AlertSink",
    "MetricsBase",
    "REGISTRY",
    "available",
    "bool_label",
    "clear_scope",
    "counter",
    "current_span_id",
    "current_trace_id",
    "emit",
    "enabled",
    "extracted_context",
    "gauge",
    "get_tracer",
    "histogram",
    "histogram_buckets_long",
    "histogram_buckets_short",
    "init_build_info",
    "inject",
    "metric_name",
    "normalize_metric_path",
    "parent_span_id_from_carrier",
    "record_exception",
    "render",
    "root_span",
    "sample_db_pool_metrics",
    "set_attributes",
    "set_request_tag",
    "set_request_user",
    "setup_sentry",
    "setup_tracing",
    "span",
    "start_http_server",
    "status_class",
]

_install_lazy_exports(__name__, _LAZY_EXPORTS)
