"""Canonical Cara exception type barrel."""

from cara._LazyExports import _install_lazy_exports

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "AccountLockedException": (".AccountLockedException", "AccountLockedException"),
    "ApiKeyInvalidException": (".ApiKeyInvalidException", "ApiKeyInvalidException"),
    "AppException": (".AppException", "AppException"),
    "AuthenticationConfigurationException": (
        ".AuthenticationConfigurationException",
        "AuthenticationConfigurationException",
    ),
    "AuthenticationException": (".AuthenticationException", "AuthenticationException"),
    "AuthorizationException": (".AuthorizationException", "AuthorizationException"),
    "AuthorizationFailedException": (
        ".AuthorizationFailedException",
        "AuthorizationFailedException",
    ),
    "BadRequestException": (".BadRequestException", "BadRequestException"),
    "BroadcastingChannelException": (
        ".BroadcastingChannelException",
        "BroadcastingChannelException",
    ),
    "BroadcastingConfigurationException": (
        ".BroadcastingConfigurationException",
        "BroadcastingConfigurationException",
    ),
    "BroadcastingConnectionException": (
        ".BroadcastingConnectionException",
        "BroadcastingConnectionException",
    ),
    "BroadcastingDriverNotFoundException": (
        ".BroadcastingDriverNotFoundException",
        "BroadcastingDriverNotFoundException",
    ),
    "BroadcastingException": (".BroadcastingException", "BroadcastingException"),
    "CacheConfigurationException": (
        ".CacheConfigurationException",
        "CacheConfigurationException",
    ),
    "CaraException": (".CaraException", "CaraException"),
    "ConfigurationException": (".ConfigurationException", "ConfigurationException"),
    "ConnectionNotRegisteredException": (
        ".ConnectionNotRegisteredException",
        "ConnectionNotRegisteredException",
    ),
    "ContainerException": (".ContainerException", "ContainerException"),
    "ControllerMethodNotFoundException": (
        ".ControllerMethodNotFoundException",
        "ControllerMethodNotFoundException",
    ),
    "DatabaseUnavailableException": (
        ".DatabaseUnavailableException",
        "DatabaseUnavailableException",
    ),
    "DriverLibraryNotFoundException": (
        ".DriverLibraryNotFoundException",
        "DriverLibraryNotFoundException",
    ),
    "DriverNotFoundException": (".DriverNotFoundException", "DriverNotFoundException"),
    "DriverNotRegisteredException": (
        ".DriverNotRegisteredException",
        "DriverNotRegisteredException",
    ),
    "EncryptionException": (".EncryptionException", "EncryptionException"),
    "EventDispatchCycleException": (
        ".EventDispatchCycleException",
        "EventDispatchCycleException",
    ),
    "EventNameConflictException": (
        ".EventNameConflictException",
        "EventNameConflictException",
    ),
    "FilterSchemaError": (".FilterSchemaError", "FilterSchemaError"),
    "FilterTreeCompileError": (".FilterTreeCompileError", "FilterTreeCompileError"),
    "FilterTreeError": (".FilterTreeError", "FilterTreeError"),
    "GenericContainerException": (
        ".GenericContainerException",
        "GenericContainerException",
    ),
    "Http404Exception": (".Http404Exception", "Http404Exception"),
    "HttpException": (".HttpException", "HttpException"),
    "IdempotencyOverlapException": (
        ".IdempotencyOverlapException",
        "IdempotencyOverlapException",
    ),
    "InvalidArgumentException": (
        ".InvalidArgumentException",
        "InvalidArgumentException",
    ),
    "InvalidConfigurationLocationException": (
        ".InvalidConfigurationLocationException",
        "InvalidConfigurationLocationException",
    ),
    "InvalidConfigurationSetupException": (
        ".InvalidConfigurationSetupException",
        "InvalidConfigurationSetupException",
    ),
    "InvalidCursor": (".InvalidCursor", "InvalidCursor"),
    "InvalidRuleFormatException": (
        ".InvalidRuleFormatException",
        "InvalidRuleFormatException",
    ),
    "InvalidTokenException": (".InvalidTokenException", "InvalidTokenException"),
    "KeyNotFoundException": (".KeyNotFoundException", "KeyNotFoundException"),
    "LazyLoadingViolation": (".LazyLoadingViolation", "LazyLoadingViolation"),
    "ListenerNotFoundException": (
        ".ListenerNotFoundException",
        "ListenerNotFoundException",
    ),
    "LoaderException": (".LoaderException", "LoaderException"),
    "LoaderNotFoundException": (".LoaderNotFoundException", "LoaderNotFoundException"),
    "MailConfigurationException": (
        ".MailConfigurationException",
        "MailConfigurationException",
    ),
    "MailDriverException": (".MailDriverException", "MailDriverException"),
    "MailException": (".MailException", "MailException"),
    "MailSendException": (".MailSendException", "MailSendException"),
    "MethodNotAllowedException": (
        ".MethodNotAllowedException",
        "MethodNotAllowedException",
    ),
    "MiddlewareException": (".MiddlewareException", "MiddlewareException"),
    "MiddlewareNotFoundException": (
        ".MiddlewareNotFoundException",
        "MiddlewareNotFoundException",
    ),
    "MigrationException": (".MigrationException", "MigrationException"),
    "MissingContainerBindingException": (
        ".MissingContainerBindingException",
        "MissingContainerBindingException",
    ),
    "ModelException": (".ModelException", "ModelException"),
    "ModelNotFoundException": (".ModelNotFoundException", "ModelNotFoundException"),
    "MultipleRecordsFoundException": (
        ".MultipleRecordsFoundException",
        "MultipleRecordsFoundException",
    ),
    "ORMException": (".ORMException", "ORMException"),
    "PayloadTooLargeException": (
        ".PayloadTooLargeException",
        "PayloadTooLargeException",
    ),
    "QueryException": (".QueryException", "QueryException"),
    "QueueConfigurationException": (
        ".QueueConfigurationException",
        "QueueConfigurationException",
    ),
    "QueueDriverLibraryNotFoundException": (
        ".QueueDriverLibraryNotFoundException",
        "QueueDriverLibraryNotFoundException",
    ),
    "QueueException": (".QueueException", "QueueException"),
    "RateLimitConfigurationException": (
        ".RateLimitConfigurationException",
        "RateLimitConfigurationException",
    ),
    "ResponseException": (".ResponseException", "ResponseException"),
    "RouteException": (".RouteException", "RouteException"),
    "RouteMiddlewareNotFoundException": (
        ".RouteMiddlewareNotFoundException",
        "RouteMiddlewareNotFoundException",
    ),
    "RouteNotFoundException": (".RouteNotFoundException", "RouteNotFoundException"),
    "RouteRegistrationException": (
        ".RouteRegistrationException",
        "RouteRegistrationException",
    ),
    "RuleNotFoundException": (".RuleNotFoundException", "RuleNotFoundException"),
    "SchedulingConfigurationException": (
        ".SchedulingConfigurationException",
        "SchedulingConfigurationException",
    ),
    "SchedulingException": (".SchedulingException", "SchedulingException"),
    "SchemaPlanRefused": (".SchemaPlanRefused", "SchemaPlanRefused"),
    "ScratchDatabaseException": (
        ".ScratchDatabaseException",
        "ScratchDatabaseException",
    ),
    "ServiceUnavailableException": (
        ".ServiceUnavailableException",
        "ServiceUnavailableException",
    ),
    "StorageConfigurationException": (
        ".StorageConfigurationException",
        "StorageConfigurationException",
    ),
    "StorageException": (".StorageException", "StorageException"),
    "StrictContainerException": (
        ".StrictContainerException",
        "StrictContainerException",
    ),
    "TokenBlacklistedException": (
        ".TokenBlacklistedException",
        "TokenBlacklistedException",
    ),
    "TokenExpiredException": (".TokenExpiredException", "TokenExpiredException"),
    "TokenInvalidException": (".TokenInvalidException", "TokenInvalidException"),
    "UnsupportedMediaTypeException": (
        ".UnsupportedMediaTypeException",
        "UnsupportedMediaTypeException",
    ),
    "UserNotFoundException": (".UserNotFoundException", "UserNotFoundException"),
    "ValidationException": (".ValidationException", "ValidationException"),
    "WebSocketException": (".WebSocketException", "WebSocketException"),
}

__all__ = [
    "AccountLockedException",
    "ApiKeyInvalidException",
    "AppException",
    "AuthenticationConfigurationException",
    "AuthenticationException",
    "AuthorizationException",
    "AuthorizationFailedException",
    "BadRequestException",
    "BroadcastingChannelException",
    "BroadcastingConfigurationException",
    "BroadcastingConnectionException",
    "BroadcastingDriverNotFoundException",
    "BroadcastingException",
    "CacheConfigurationException",
    "CaraException",
    "ConfigurationException",
    "ConnectionNotRegisteredException",
    "ContainerException",
    "ControllerMethodNotFoundException",
    "DatabaseUnavailableException",
    "DriverLibraryNotFoundException",
    "DriverNotFoundException",
    "DriverNotRegisteredException",
    "EncryptionException",
    "EventDispatchCycleException",
    "EventNameConflictException",
    "FilterSchemaError",
    "FilterTreeCompileError",
    "FilterTreeError",
    "GenericContainerException",
    "Http404Exception",
    "HttpException",
    "IdempotencyOverlapException",
    "InvalidArgumentException",
    "InvalidConfigurationLocationException",
    "InvalidConfigurationSetupException",
    "InvalidCursor",
    "InvalidRuleFormatException",
    "InvalidTokenException",
    "KeyNotFoundException",
    "LazyLoadingViolation",
    "ListenerNotFoundException",
    "LoaderException",
    "LoaderNotFoundException",
    "MailConfigurationException",
    "MailDriverException",
    "MailException",
    "MailSendException",
    "MethodNotAllowedException",
    "MiddlewareException",
    "MiddlewareNotFoundException",
    "MigrationException",
    "MissingContainerBindingException",
    "ModelException",
    "ModelNotFoundException",
    "MultipleRecordsFoundException",
    "ORMException",
    "PayloadTooLargeException",
    "QueryException",
    "QueueConfigurationException",
    "QueueDriverLibraryNotFoundException",
    "QueueException",
    "RateLimitConfigurationException",
    "ResponseException",
    "RouteException",
    "RouteMiddlewareNotFoundException",
    "RouteNotFoundException",
    "RouteRegistrationException",
    "RuleNotFoundException",
    "SchedulingConfigurationException",
    "SchedulingException",
    "SchemaPlanRefused",
    "ScratchDatabaseException",
    "ServiceUnavailableException",
    "StorageConfigurationException",
    "StorageException",
    "StrictContainerException",
    "TokenBlacklistedException",
    "TokenExpiredException",
    "TokenInvalidException",
    "UnsupportedMediaTypeException",
    "UserNotFoundException",
    "ValidationException",
    "WebSocketException",
]

_install_lazy_exports(__name__, _LAZY_EXPORTS)
