"""Exact zero-debt census for cara's own Guard Pack (§11).

Generated by ``_cara_self_scan.render_census()``. Every self-scanned rule is
kept here explicitly so adding a scanner still requires an intentional
decision, while any future finding fails rather than entering an allowlist.
"""

from __future__ import annotations

CENSUS: dict[str, dict[str, int]] = {
    "import_tiers": {},
    "inline_imports": {},
    "import_form": {},
    "source_shape": {},
    "barrel_completeness": {},
    "collaborator_calls": {},
    "barrel_mid_load": {},
    "silent_except_swallow": {},
}
