"""
Support Module Initialization.

This module provides core support classes and utilities for the Cara framework. It includes the
Collection class which offers a fluent, Laravel-style interface for working with arrays and data
collections.
"""

from cara._LazyExports import _install_lazy_exports

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "AnsiColors": (".AnsiColors", "AnsiColors"),
    "Collection": (".Collection", "Collection"),
    "CurrencyMismatch": (".CurrencyMismatch", "CurrencyMismatch"),
    "DEFAULT_SMTP_PORT": (".MailSafety", "DEFAULT_SMTP_PORT"),
    "Date": (".Date", "Date"),
    "HTTP_STATUS_CODES": (".Http", "HTTP_STATUS_CODES"),
    "HasColoredOutput": (".HasColoredOutput", "HasColoredOutput"),
    "HtmlString": (".HtmlString", "HtmlString"),
    "Image": (".Image", "Image"),
    "ImageProcessor": (".ImageProcessor", "ImageProcessor"),
    "KNOWN_MIME_TYPES": (".Filesystem", "KNOWN_MIME_TYPES"),
    "LIKE_ESCAPE_CHAR": (".LikeEscape", "LIKE_ESCAPE_CHAR"),
    "LogColors": (".LogColors", "LogColors"),
    "LogType": (".LogType", "LogType"),
    "Macroable": (".Macroable", "Macroable"),
    "Manager": (".Manager", "Manager"),
    "ModuleManager": (".ModuleManager", "ModuleManager"),
    "Money": (".Money", "Money"),
    "Pipeline": (".Pipeline", "Pipeline"),
    "Process": (".Process", "Process"),
    "ProcessFailedException": (".ProcessFailedException", "ProcessFailedException"),
    "ProcessFileLock": (".ProcessFileLock", "ProcessFileLock"),
    "ProcessResult": (".ProcessResult", "ProcessResult"),
    "Retry": (".Retry", "Retry"),
    "RetryBuilder": (".RetryBuilder", "RetryBuilder"),
    "ReturnPath": (".ReturnPath", "ReturnPath"),
    "SECONDS_PER_DAY": (".Time", "SECONDS_PER_DAY"),
    "SMTP_TIMEOUT_SECONDS": (".MailSafety", "SMTP_TIMEOUT_SECONDS"),
    "Sleep": (".Sleep", "Sleep"),
    "SupportProvider": (".SupportProvider", "SupportProvider"),
    "as_filepath": (".Str", "as_filepath"),
    "authenticated_user": (".Auth", "authenticated_user"),
    "base_path": (".Paths", "base_path"),
    "best_effort": (".BestEffort", "best_effort"),
    "best_effort_ctx": (".BestEffort", "best_effort_ctx"),
    "callable_only": (".Pipeline", "callable_only"),
    "collect": (".Collection", "collect"),
    "creation_date": (".Filesystem", "creation_date"),
    "csv_filter_values": (".FilterValues", "csv_filter_values"),
    "currency_symbol": (".Currency", "currency_symbol"),
    "data": (".Structures", "data"),
    "data_get": (".Structures", "data_get"),
    "data_set": (".Structures", "data_set"),
    "decimal_text": (".Number", "decimal_text"),
    "decimal_to_wire": (".JsonEncoding", "decimal_to_wire"),
    "defuse_csv_cell": (".CsvSafe", "defuse_csv_cell"),
    "email_mask": (".Str", "email_mask"),
    "escape_like": (".LikeEscape", "escape_like"),
    "file_exists": (".Filesystem", "file_exists"),
    "flatten": (".Collection", "flatten"),
    "format_money": (".Currency", "format_money"),
    "gate_allows": (".Auth", "gate_allows"),
    "get_classes": (".Modules", "get_classes"),
    "get_extension": (".Filesystem", "get_extension"),
    "get_module_dir": (".Filesystem", "get_module_dir"),
    "is_public_id": (".PublicIds", "is_public_id"),
    "is_public_id_prefix": (".PublicIds", "is_public_id_prefix"),
    "iso_datetime": (".DateSerialization", "iso_datetime"),
    "json_default": (".JsonEncoding", "json_default"),
    "json_dumps": (".JsonEncoding", "json_dumps"),
    "like_contains": (".LikeEscape", "like_contains"),
    "load": (".ModuleLoader", "load"),
    "make_directory": (".Filesystem", "make_directory"),
    "make_full_directory": (".Filesystem", "make_full_directory"),
    "margin_ratio": (".Money", "margin_ratio"),
    "markup_ratio": (".Money", "markup_ratio"),
    "mask_ip": (".Str", "mask_ip"),
    "mask_proxy_url": (".Str", "mask_proxy_url"),
    "mask_token": (".Str", "mask_token"),
    "modified_date": (".Filesystem", "modified_date"),
    "modularize": (".Str", "modularize"),
    "modules": (".Modules", "modules"),
    "normalize_currency_code": (".Currency", "normalize_currency_code"),
    "optional_user_id": (".Auth", "optional_user_id"),
    "parse_decimal_text": (".Number", "parse_decimal_text"),
    "parse_human_time": (".Time", "parse_human_time"),
    "paths": (".Paths", "paths"),
    "public_path": (".Paths", "public_path"),
    "redact_log_secrets": (".Str", "redact_log_secrets"),
    "removesuffix": (".Str", "removesuffix"),
    "render_stub_file": (".Filesystem", "render_stub_file"),
    "require_currency_code": (".Currency", "require_currency_code"),
    "resolve_user": (".Auth", "resolve_user"),
    "safe_divide_decimal": (".Number", "safe_divide_decimal"),
    "safe_float": (".Coercion", "safe_float"),
    "safe_int": (".Coercion", "safe_int"),
    "sanitize_text": (".Str", "sanitize_text"),
    "slugify": (".Str", "slugify"),
    "storage_path": (".Paths", "storage_path"),
    "strip_header_crlf": (".MailSafety", "strip_header_crlf"),
    "strip_tags": (".Str", "strip_tags"),
    "to_decimal": (".Number", "to_decimal"),
    "to_decimal_or_none": (".Number", "to_decimal_or_none"),
    "to_pendulum": (".Time", "to_pendulum"),
    "trusted_client_ip": (".ClientIp", "trusted_client_ip"),
    "user_id": (".Auth", "user_id"),
    "validate_path_param": (".RequestPath", "validate_path_param"),
}

__all__ = [
    "AnsiColors",
    "Collection",
    "CurrencyMismatch",
    "DEFAULT_SMTP_PORT",
    "Date",
    "HTTP_STATUS_CODES",
    "HasColoredOutput",
    "HtmlString",
    "Image",
    "ImageProcessor",
    "KNOWN_MIME_TYPES",
    "LIKE_ESCAPE_CHAR",
    "LogColors",
    "LogType",
    "Macroable",
    "Manager",
    "ModuleManager",
    "Money",
    "Pipeline",
    "Process",
    "ProcessFailedException",
    "ProcessFileLock",
    "ProcessResult",
    "Retry",
    "RetryBuilder",
    "ReturnPath",
    "SECONDS_PER_DAY",
    "SMTP_TIMEOUT_SECONDS",
    "Sleep",
    "SupportProvider",
    "as_filepath",
    "authenticated_user",
    "base_path",
    "best_effort",
    "best_effort_ctx",
    "callable_only",
    "collect",
    "creation_date",
    "csv_filter_values",
    "currency_symbol",
    "data",
    "data_get",
    "data_set",
    "decimal_text",
    "decimal_to_wire",
    "defuse_csv_cell",
    "email_mask",
    "escape_like",
    "file_exists",
    "flatten",
    "format_money",
    "gate_allows",
    "get_classes",
    "get_extension",
    "get_module_dir",
    "is_public_id",
    "is_public_id_prefix",
    "iso_datetime",
    "json_default",
    "json_dumps",
    "like_contains",
    "load",
    "make_directory",
    "make_full_directory",
    "margin_ratio",
    "markup_ratio",
    "mask_ip",
    "mask_proxy_url",
    "mask_token",
    "modified_date",
    "modularize",
    "modules",
    "normalize_currency_code",
    "optional_user_id",
    "parse_decimal_text",
    "parse_human_time",
    "paths",
    "public_path",
    "redact_log_secrets",
    "removesuffix",
    "render_stub_file",
    "require_currency_code",
    "resolve_user",
    "safe_divide_decimal",
    "safe_float",
    "safe_int",
    "sanitize_text",
    "slugify",
    "storage_path",
    "strip_header_crlf",
    "strip_tags",
    "to_decimal",
    "to_decimal_or_none",
    "to_pendulum",
    "trusted_client_ip",
    "user_id",
    "validate_path_param",
]

_install_lazy_exports(__name__, _LAZY_EXPORTS)
