"""cara.architecture — the Guard Pack (DOCTRINE §11).

"The pack converges on ONE implementation. Guard logic (the AST scanners)
belongs in the framework; products supply only their manifests." A product
wires one :class:`Manifest` per deployable (``app/architecture_manifest.py``)
and gets every scanner in :mod:`cara.architecture.scanners`, the shared
:class:`ImportGraph` and :class:`BarrelGenerator` tools, and the
``craft arch:check`` / ``craft arch:barrels`` commands, all boot-free.
"""

from cara._LazyExports import _install_lazy_exports

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "ABORT_CALL": (".scanners", "ABORT_CALL"),
    "BROAD_EXCEPTIONS": (".scanners", "BROAD_EXCEPTIONS"),
    "BarrelCompleteness": (".scanners", "BarrelCompleteness"),
    "BarrelGenerator": (".BarrelGenerator", "BarrelGenerator"),
    "BarrelMidLoad": (".scanners", "BarrelMidLoad"),
    "BarrelPlan": (".BarrelPlan", "BarrelPlan"),
    "CLASSES_KEY": (".scanners", "CLASSES_KEY"),
    "COLLABORATOR_CALLS_KEY": (".scanners", "COLLABORATOR_CALLS_KEY"),
    "COMPOSE_METHODS": (".scanners", "COMPOSE_METHODS"),
    "CURSOR_EXEC_METHODS": (".scanners", "CURSOR_EXEC_METHODS"),
    "CYCLE_PREFIX": (".scanners", "CYCLE_PREFIX"),
    "CollaboratorCalls": (".scanners", "CollaboratorCalls"),
    "DOMAIN_OWNERSHIP_KEY": (".scanners", "DOMAIN_OWNERSHIP_KEY"),
    "DomainOwnership": (".scanners", "DomainOwnership"),
    "DomainRegistry": (".scanners", "DomainRegistry"),
    "DryRunResult": (".DryRunResult", "DryRunResult"),
    "EDGE_METHODS_KEY": (".scanners", "EDGE_METHODS_KEY"),
    "ENVIRONMENT_MODULE": (".scanners", "ENVIRONMENT_MODULE"),
    "EXEC_METHODS": (".scanners", "EXEC_METHODS"),
    "EnvReadDiscipline": (".scanners", "EnvReadDiscipline"),
    "FLOW_KEY": (".scanners", "FLOW_KEY"),
    "Finding": (".Finding", "Finding"),
    "FlowLaw": (".scanners", "FlowLaw"),
    "HttpInBusinessLogic": (".scanners", "HttpInBusinessLogic"),
    "ImportForm": (".scanners", "ImportForm"),
    "ImportGraph": (".ImportGraph", "ImportGraph"),
    "ImportTiers": (".scanners", "ImportTiers"),
    "InlineImports": (".scanners", "InlineImports"),
    "JobIdempotency": (".scanners", "JobIdempotency"),
    "KernelMembership": (".scanners", "KernelMembership"),
    "LEGAL_PREFIXES": (".scanners", "LEGAL_PREFIXES"),
    "LINES_KEY": (".scanners", "LINES_KEY"),
    "MAX_LINE": (".BarrelGenerator", "MAX_LINE"),
    "Manifest": (".Manifest", "Manifest"),
    "ManifestRoots": (".ManifestRoots", "ManifestRoots"),
    "ModelQueryDiscipline": (".scanners", "ModelQueryDiscipline"),
    "ORM_METHODS": (".scanners", "ORM_METHODS"),
    "OS_ENV_NAMES": (".scanners", "OS_ENV_NAMES"),
    "OWNERS": (".scanners", "OWNERS"),
    "PORTS_LAYER": (".scanners", "PORTS_LAYER"),
    "PortMembership": (".scanners", "PortMembership"),
    "QUERY_COMPILER_MARKER": (".scanners", "QUERY_COMPILER_MARKER"),
    "REGISTRY": (".scanners", "REGISTRY"),
    "REPORTING_CALLS": (".scanners", "REPORTING_CALLS"),
    "ROW_LOCK_METHOD": (".scanners", "ROW_LOCK_METHOD"),
    "RawSqlHome": (".scanners", "RawSqlHome"),
    "SQL_START": (".scanners", "SQL_START"),
    "STDLIB": ("._ast_utils", "STDLIB"),
    "SeamLocations": (".SeamLocations", "SeamLocations"),
    "SilentExceptSwallow": (".scanners", "SilentExceptSwallow"),
    "SourceShape": (".scanners", "SourceShape"),
    "TAG": (".scanners", "TAG"),
    "TRANSACTION_KEY": (".scanners", "TRANSACTION_KEY"),
    "TRANSACTION_METHOD": (".scanners", "TRANSACTION_METHOD"),
    "TransactionOwnership": (".scanners", "TransactionOwnership"),
    "VendorBarrelParity": (".scanners", "VendorBarrelParity"),
    "VendorDryRun": (".VendorDryRun", "VendorDryRun"),
    "VerticalSliceSeams": (".scanners", "VerticalSliceSeams"),
    "WRITE_KEY": (".scanners", "WRITE_KEY"),
    "WriteOwnership": (".scanners", "WriteOwnership"),
    "all_nodes": ("._ast_utils", "all_nodes"),
    "clear_parse_cache": ("._ast_utils", "clear_parse_cache"),
    "declared_all": ("._ast_utils", "declared_all"),
    "declares_dunder_all": ("._ast_utils", "declares_dunder_all"),
    "docstring_node_ids": ("._ast_utils", "docstring_node_ids"),
    "dunder_all": ("._ast_utils", "dunder_all"),
    "function_local_imports": ("._ast_utils", "function_local_imports"),
    "is_module_object": ("._ast_utils", "is_module_object"),
    "is_type_checking_if": ("._ast_utils", "is_type_checking_if"),
    "is_upper_const": ("._ast_utils", "is_upper_const"),
    "iter_modules": ("._ast_utils", "iter_modules"),
    "module_level_imports": ("._ast_utils", "module_level_imports"),
    "module_object_names": ("._ast_utils", "module_object_names"),
    "parse": ("._ast_utils", "parse"),
    "public_names": ("._ast_utils", "public_names"),
    "python_files": ("._ast_utils", "python_files"),
    "query_compiler_classes": (".scanners", "query_compiler_classes"),
    "raw_sql_findings": (".scanners", "raw_sql_findings"),
    "read_source": ("._ast_utils", "read_source"),
    "relpath": ("._ast_utils", "relpath"),
}

__all__ = [
    "ABORT_CALL",
    "BROAD_EXCEPTIONS",
    "BarrelCompleteness",
    "BarrelGenerator",
    "BarrelMidLoad",
    "BarrelPlan",
    "CLASSES_KEY",
    "COLLABORATOR_CALLS_KEY",
    "COMPOSE_METHODS",
    "CURSOR_EXEC_METHODS",
    "CYCLE_PREFIX",
    "CollaboratorCalls",
    "DOMAIN_OWNERSHIP_KEY",
    "DomainOwnership",
    "DomainRegistry",
    "DryRunResult",
    "EDGE_METHODS_KEY",
    "ENVIRONMENT_MODULE",
    "EXEC_METHODS",
    "EnvReadDiscipline",
    "FLOW_KEY",
    "Finding",
    "FlowLaw",
    "HttpInBusinessLogic",
    "ImportForm",
    "ImportGraph",
    "ImportTiers",
    "InlineImports",
    "JobIdempotency",
    "KernelMembership",
    "LEGAL_PREFIXES",
    "LINES_KEY",
    "MAX_LINE",
    "Manifest",
    "ManifestRoots",
    "ModelQueryDiscipline",
    "ORM_METHODS",
    "OS_ENV_NAMES",
    "OWNERS",
    "PORTS_LAYER",
    "PortMembership",
    "QUERY_COMPILER_MARKER",
    "REGISTRY",
    "REPORTING_CALLS",
    "ROW_LOCK_METHOD",
    "RawSqlHome",
    "SQL_START",
    "STDLIB",
    "SeamLocations",
    "SilentExceptSwallow",
    "SourceShape",
    "TAG",
    "TRANSACTION_KEY",
    "TRANSACTION_METHOD",
    "TransactionOwnership",
    "VendorBarrelParity",
    "VendorDryRun",
    "VerticalSliceSeams",
    "WRITE_KEY",
    "WriteOwnership",
    "all_nodes",
    "clear_parse_cache",
    "declared_all",
    "declares_dunder_all",
    "docstring_node_ids",
    "dunder_all",
    "function_local_imports",
    "is_module_object",
    "is_type_checking_if",
    "is_upper_const",
    "iter_modules",
    "module_level_imports",
    "module_object_names",
    "parse",
    "public_names",
    "python_files",
    "query_compiler_classes",
    "raw_sql_findings",
    "read_source",
    "relpath",
]

_install_lazy_exports(__name__, _LAZY_EXPORTS)
