"""``HttpConductor._run_terminable_middleware`` + ``ParameterizedMiddleware``
``terminate`` — sync vs async dispatch.

The bug
-------
Both call sites blind-awaited the ``terminate`` return value:

  * ``HttpConductor._run_terminable_middleware`` did
    ``await terminate_fn(request, response)``.
  * The ``ParameterizedMiddleware`` proxy class generated by
    ``MiddlewareCapsule._create_parameterized_middleware`` did
    ``await self._instance.terminate(request, response)``.

When the wrapped middleware's ``terminate`` is **synchronous**
(``def terminate(self, ...): ...`` returning None), ``await None``
raises::

    TypeError: object NoneType can't be used in 'await' expression

The conductor's broad ``except Exception`` then logs an opaque
"Error in terminable middleware X" and silently skips the
terminate step. The framework's own contract (mirrored in
``cara.support.Pipeline``) accepts both sync and async pipes, so
user-land middleware with a ``def terminate`` (synchronous
cleanup — closing a request-scoped resource, decrementing an
in-process counter, flushing a metrics buffer) was a documented-
to-work shape that silently no-op'd on every request.

The fix
-------
Mirror ``cara.support.Pipeline``'s dispatch: call the function,
inspect the result, ``await`` ONLY if awaitable. Both async (the
existing built-in ``ResetAuth``) and sync (user-land) terminate
shapes now run cleanly.

Tests pin:
  - Sync terminate executes (no TypeError, no opaque log).
  - Async terminate still works (regression guard).
  - Mixed sync + async middlewares all run; one's failure mode
    doesn't mask another.
  - ``ParameterizedMiddleware.terminate`` accepts both shapes
    on the wrapped instance.
"""

from __future__ import annotations

import asyncio
import importlib
from typing import Any

import pytest


_conductor_mod = importlib.import_module("cara.conductors.http.HttpConductor")
_capsule_mod = importlib.import_module("cara.middleware.MiddlewareCapsule")


# ── Stubs ──────────────────────────────────────────────────────


class _SyncTerminate:
    """User-land middleware with a synchronous ``terminate`` —
    typical shape when the cleanup is in-process (counter
    decrement, dict pop, file handle close) and doesn't need an
    event-loop yield."""

    def __init__(self) -> None:
        self.calls: list[tuple] = []

    async def handle(self, request: Any, next_fn: Any) -> Any:
        return await next_fn(request)

    def terminate(self, request: Any, response: Any) -> None:
        # Sync — returns None. Pre-fix the conductor's ``await None``
        # raised TypeError and the call was logged + skipped.
        self.calls.append((request, response))


class _AsyncTerminate:
    """Reference shape — async terminate. Both built-in
    ``ResetAuth`` and most user middleware follow this."""

    def __init__(self) -> None:
        self.calls: list[tuple] = []

    async def handle(self, request: Any, next_fn: Any) -> Any:
        return await next_fn(request)

    async def terminate(self, request: Any, response: Any) -> None:
        self.calls.append((request, response))


class _NoTerminate:
    """Middleware without a ``terminate`` at all — must be skipped
    silently. Regression guard against the dispatcher accidentally
    crashing on a missing method (which the ``getattr(..., None)``
    + ``callable(...)`` checks were supposed to handle)."""

    async def handle(self, request: Any, next_fn: Any) -> Any:
        return await next_fn(request)


class _FakeRequest:
    pass


class _FakeResponse:
    pass


class _StubResetAuth:
    """Stand-in for the conductor's hardcoded ``ResetAuth`` cleanup
    call. The real one needs an application instance + auth cache
    facade; we just want a no-op that doesn't blow up the test."""

    def __init__(self, _app: Any) -> None:
        pass

    async def terminate(self, _req: Any, _resp: Any) -> None:
        return None


class _StubPipeline:
    """Mimics the parts of ``Pipeline`` the conductor's
    ``_run_terminable_middleware`` reaches into — just the
    ``executed_instances`` attribute."""

    def __init__(self, instances: list[Any]) -> None:
        self.executed_instances = instances


# ── _run_terminable_middleware ────────────────────────────────


def _conductor(monkeypatch: pytest.MonkeyPatch):
    """Build a minimal HttpConductor bypassing __init__ so we don't
    need the application's full DI graph for these tests. Stub
    ``ResetAuth`` so the hardcoded auth-cache cleanup call doesn't
    crash."""
    monkeypatch.setattr(_conductor_mod, "ResetAuth", _StubResetAuth)
    HttpConductor = _conductor_mod.HttpConductor
    conductor = HttpConductor.__new__(HttpConductor)
    conductor.application = None  # ResetAuth stub doesn't use it
    return conductor


class TestSyncTerminateRunsCleanly:
    def test_sync_terminate_executes_without_typeerror(
        self,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        conductor = _conductor(monkeypatch)
        sync_mw = _SyncTerminate()
        pipeline = _StubPipeline([sync_mw])
        req, resp = _FakeRequest(), _FakeResponse()

        asyncio.run(
            conductor._run_terminable_middleware(
                req,
                resp,
                pipeline,
                None,
            )
        )

        assert sync_mw.calls == [(req, resp)], (
            "sync terminate must have been called exactly once; "
            "pre-fix ``await None`` raised TypeError, conductor's "
            "broad except swallowed it, and the call was silently "
            f"skipped. Calls observed: {sync_mw.calls!r}"
        )


class TestAsyncTerminateStillWorks:
    """Regression guard — the existing async ``ResetAuth`` path
    must not break under the new dispatcher."""

    def test_async_terminate_executes(
        self,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        conductor = _conductor(monkeypatch)
        async_mw = _AsyncTerminate()
        pipeline = _StubPipeline([async_mw])
        req, resp = _FakeRequest(), _FakeResponse()

        asyncio.run(
            conductor._run_terminable_middleware(
                req,
                resp,
                pipeline,
                None,
            )
        )

        assert async_mw.calls == [(req, resp)]


class TestMixedStackRunsAll:
    def test_sync_async_no_terminate_all_handled(
        self,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """A realistic stack has all three shapes. None of them should
        block another — pre-fix the sync one's TypeError, caught and
        logged, didn't break the loop, but it WAS silently skipped.
        After the fix all three behave correctly."""
        conductor = _conductor(monkeypatch)
        sync_mw = _SyncTerminate()
        async_mw = _AsyncTerminate()
        no_term = _NoTerminate()
        pipeline = _StubPipeline([sync_mw, no_term, async_mw])
        req, resp = _FakeRequest(), _FakeResponse()

        asyncio.run(
            conductor._run_terminable_middleware(
                req,
                resp,
                pipeline,
                None,
            )
        )

        # Sync ran exactly once.
        assert sync_mw.calls == [(req, resp)]
        # Async ran exactly once.
        assert async_mw.calls == [(req, resp)]
        # No-terminate was just skipped (no crash, no calls to
        # assert against — the absence of the method is the signal).

    def test_one_middleware_raising_does_not_block_others(
        self,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """Defense-in-depth: a buggy middleware's terminate raises
        a real exception (NOT the TypeError-from-blind-await — a
        genuine bug in user code). The dispatcher must catch it
        and continue to the next middleware. Existing contract;
        pin so the fix doesn't accidentally regress it."""
        conductor = _conductor(monkeypatch)

        class _RaisingTerminate:
            async def handle(self, req: Any, next_fn: Any) -> Any:
                return await next_fn(req)

            def terminate(self, _req: Any, _resp: Any) -> None:
                raise RuntimeError("user-land bug")

        raising_mw = _RaisingTerminate()
        async_mw = _AsyncTerminate()
        pipeline = _StubPipeline([raising_mw, async_mw])
        req, resp = _FakeRequest(), _FakeResponse()

        # Must NOT raise — the conductor logs and continues.
        asyncio.run(
            conductor._run_terminable_middleware(
                req,
                resp,
                pipeline,
                None,
            )
        )

        # The downstream async one still ran despite the upstream
        # crash.
        assert async_mw.calls == [(req, resp)]


# ── ParameterizedMiddleware proxy ─────────────────────────────


class TestParameterizedProxyTerminateShape:
    """The ``ParameterizedMiddleware`` proxy at
    ``MiddlewareCapsule._create_parameterized_middleware`` had
    the same blind-await bug. Routes using parameterised middleware
    — ``throttle:60,1``, ``auth:jwt`` etc. — get the proxy.
    If the underlying middleware has a sync ``terminate``, the
    proxy crashed."""

    def _build_proxy(self, base_cls: type) -> Any:
        # The capsule helper is a method on MiddlewareCapsule that
        # builds the proxy class. Call it through a bare instance
        # bypassing __init__ — we don't need a real application.
        capsule = _capsule_mod.MiddlewareCapsule.__new__(_capsule_mod.MiddlewareCapsule)
        capsule.application = None
        return capsule._create_parameterized_middleware(base_cls, [])

    def test_proxy_terminate_handles_sync_wrapped(self) -> None:
        """Proxy must accept a sync wrapped terminate."""
        calls: list = []

        class _Base:
            def __init__(self, _app: Any) -> None:
                pass

            @classmethod
            def create_with_parameters(cls, app: Any, _params: list) -> "_Base":
                return cls(app)

            async def handle(self, req: Any, next_fn: Any) -> Any:
                return await next_fn(req)

            def terminate(self, req: Any, resp: Any) -> None:
                calls.append((req, resp))

        ProxyCls = self._build_proxy(_Base)
        proxy = ProxyCls(application=None)
        req, resp = _FakeRequest(), _FakeResponse()

        # Pre-fix this raised TypeError on ``await None``.
        asyncio.run(proxy.terminate(req, resp))
        assert calls == [(req, resp)]

    def test_proxy_terminate_handles_async_wrapped(self) -> None:
        """Regression — async wrapped path still works."""
        calls: list = []

        class _Base:
            def __init__(self, _app: Any) -> None:
                pass

            @classmethod
            def create_with_parameters(cls, app: Any, _params: list) -> "_Base":
                return cls(app)

            async def handle(self, req: Any, next_fn: Any) -> Any:
                return await next_fn(req)

            async def terminate(self, req: Any, resp: Any) -> None:
                calls.append((req, resp))

        ProxyCls = self._build_proxy(_Base)
        proxy = ProxyCls(application=None)
        req, resp = _FakeRequest(), _FakeResponse()

        asyncio.run(proxy.terminate(req, resp))
        assert calls == [(req, resp)]

    def test_proxy_terminate_no_terminate_on_base_noop(self) -> None:
        """Base without ``terminate`` — proxy ``terminate`` is a
        no-op (the ``if hasattr`` gate handles it). Pin so a
        future tightening doesn't turn missing-method into an
        AttributeError."""

        class _Base:
            def __init__(self, _app: Any) -> None:
                pass

            @classmethod
            def create_with_parameters(cls, app: Any, _params: list) -> "_Base":
                return cls(app)

            async def handle(self, req: Any, next_fn: Any) -> Any:
                return await next_fn(req)

            # No terminate method.

        ProxyCls = self._build_proxy(_Base)
        proxy = ProxyCls(application=None)
        # Must not raise.
        asyncio.run(proxy.terminate(_FakeRequest(), _FakeResponse()))
