"""Canonical Cara exception registry."""

from __future__ import annotations

from cara._LazyExports import _install_lazy_exports

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "AccountLockedException": (".types", "AccountLockedException"),
    "ApiKeyInvalidException": (".types", "ApiKeyInvalidException"),
    "AppException": (".types", "AppException"),
    "AuthenticationConfigurationException": (
        ".types",
        "AuthenticationConfigurationException",
    ),
    "AuthenticationException": (".types", "AuthenticationException"),
    "AuthorizationException": (".types", "AuthorizationException"),
    "AuthorizationFailedException": (".types", "AuthorizationFailedException"),
    "BadRequestException": (".types", "BadRequestException"),
    "BroadcastingChannelException": (".types", "BroadcastingChannelException"),
    "BroadcastingConfigurationException": (
        ".types",
        "BroadcastingConfigurationException",
    ),
    "BroadcastingConnectionException": (".types", "BroadcastingConnectionException"),
    "BroadcastingDriverNotFoundException": (
        ".types",
        "BroadcastingDriverNotFoundException",
    ),
    "BroadcastingException": (".types", "BroadcastingException"),
    "CacheConfigurationException": (".types", "CacheConfigurationException"),
    "CaraException": (".types", "CaraException"),
    "ConfigurationException": (".types", "ConfigurationException"),
    "ConnectionNotRegisteredException": (".types", "ConnectionNotRegisteredException"),
    "ContainerException": (".types", "ContainerException"),
    "ControllerMethodNotFoundException": (
        ".types",
        "ControllerMethodNotFoundException",
    ),
    "DatabaseUnavailableException": (".types", "DatabaseUnavailableException"),
    "DefaultExceptionHandler": (".handlers", "DefaultExceptionHandler"),
    "DriverLibraryNotFoundException": (".types", "DriverLibraryNotFoundException"),
    "DriverNotFoundException": (".types", "DriverNotFoundException"),
    "DriverNotRegisteredException": (".types", "DriverNotRegisteredException"),
    "EncryptionException": (".types", "EncryptionException"),
    "EventDispatchCycleException": (".types", "EventDispatchCycleException"),
    "EventNameConflictException": (".types", "EventNameConflictException"),
    "FilterSchemaError": (".types", "FilterSchemaError"),
    "FilterTreeCompileError": (".types", "FilterTreeCompileError"),
    "FilterTreeError": (".types", "FilterTreeError"),
    "GenericContainerException": (".types", "GenericContainerException"),
    "Http404Exception": (".types", "Http404Exception"),
    "HttpException": (".types", "HttpException"),
    "IdempotencyOverlapException": (".types", "IdempotencyOverlapException"),
    "InvalidArgumentException": (".types", "InvalidArgumentException"),
    "InvalidConfigurationLocationException": (
        ".types",
        "InvalidConfigurationLocationException",
    ),
    "InvalidConfigurationSetupException": (
        ".types",
        "InvalidConfigurationSetupException",
    ),
    "InvalidCursor": (".types", "InvalidCursor"),
    "InvalidRuleFormatException": (".types", "InvalidRuleFormatException"),
    "InvalidTokenException": (".types", "InvalidTokenException"),
    "KeyNotFoundException": (".types", "KeyNotFoundException"),
    "LazyLoadingViolation": (".types", "LazyLoadingViolation"),
    "ListenerNotFoundException": (".types", "ListenerNotFoundException"),
    "LoaderException": (".types", "LoaderException"),
    "LoaderNotFoundException": (".types", "LoaderNotFoundException"),
    "MailConfigurationException": (".types", "MailConfigurationException"),
    "MailDriverException": (".types", "MailDriverException"),
    "MailException": (".types", "MailException"),
    "MailSendException": (".types", "MailSendException"),
    "MethodNotAllowedException": (".types", "MethodNotAllowedException"),
    "MiddlewareException": (".types", "MiddlewareException"),
    "MiddlewareNotFoundException": (".types", "MiddlewareNotFoundException"),
    "MigrationException": (".types", "MigrationException"),
    "MissingContainerBindingException": (".types", "MissingContainerBindingException"),
    "ModelException": (".types", "ModelException"),
    "ModelNotFoundException": (".types", "ModelNotFoundException"),
    "MultipleRecordsFoundException": (".types", "MultipleRecordsFoundException"),
    "ORMException": (".types", "ORMException"),
    "PayloadTooLargeException": (".types", "PayloadTooLargeException"),
    "QueryException": (".types", "QueryException"),
    "QueueConfigurationException": (".types", "QueueConfigurationException"),
    "QueueDriverLibraryNotFoundException": (
        ".types",
        "QueueDriverLibraryNotFoundException",
    ),
    "QueueException": (".types", "QueueException"),
    "RateLimitConfigurationException": (".types", "RateLimitConfigurationException"),
    "ResponseException": (".types", "ResponseException"),
    "RouteException": (".types", "RouteException"),
    "RouteMiddlewareNotFoundException": (".types", "RouteMiddlewareNotFoundException"),
    "RouteNotFoundException": (".types", "RouteNotFoundException"),
    "RouteRegistrationException": (".types", "RouteRegistrationException"),
    "RuleNotFoundException": (".types", "RuleNotFoundException"),
    "SchedulingConfigurationException": (".types", "SchedulingConfigurationException"),
    "SchedulingException": (".types", "SchedulingException"),
    "SchemaPlanRefused": (".types", "SchemaPlanRefused"),
    "ScratchDatabaseException": (".types", "ScratchDatabaseException"),
    "ServiceUnavailableException": (".types", "ServiceUnavailableException"),
    "StorageConfigurationException": (".types", "StorageConfigurationException"),
    "StorageException": (".types", "StorageException"),
    "StrictContainerException": (".types", "StrictContainerException"),
    "TokenBlacklistedException": (".types", "TokenBlacklistedException"),
    "TokenExpiredException": (".types", "TokenExpiredException"),
    "TokenInvalidException": (".types", "TokenInvalidException"),
    "UnsupportedMediaTypeException": (".types", "UnsupportedMediaTypeException"),
    "UserNotFoundException": (".types", "UserNotFoundException"),
    "ValidationException": (".types", "ValidationException"),
    "WebSocketException": (".types", "WebSocketException"),
    "validate_exception_envelopes": (".Envelopes", "validate_exception_envelopes"),
}

__all__ = [
    "AccountLockedException",
    "ApiKeyInvalidException",
    "AppException",
    "AuthenticationConfigurationException",
    "AuthenticationException",
    "AuthorizationException",
    "AuthorizationFailedException",
    "BadRequestException",
    "BroadcastingChannelException",
    "BroadcastingConfigurationException",
    "BroadcastingConnectionException",
    "BroadcastingDriverNotFoundException",
    "BroadcastingException",
    "CacheConfigurationException",
    "CaraException",
    "ConfigurationException",
    "ConnectionNotRegisteredException",
    "ContainerException",
    "ControllerMethodNotFoundException",
    "DatabaseUnavailableException",
    "DefaultExceptionHandler",
    "DriverLibraryNotFoundException",
    "DriverNotFoundException",
    "DriverNotRegisteredException",
    "EncryptionException",
    "EventDispatchCycleException",
    "EventNameConflictException",
    "ExceptionProvider",
    "FilterSchemaError",
    "FilterTreeCompileError",
    "FilterTreeError",
    "GenericContainerException",
    "Http404Exception",
    "HttpException",
    "IdempotencyOverlapException",
    "InvalidArgumentException",
    "InvalidConfigurationLocationException",
    "InvalidConfigurationSetupException",
    "InvalidCursor",
    "InvalidRuleFormatException",
    "InvalidTokenException",
    "KeyNotFoundException",
    "LazyLoadingViolation",
    "ListenerNotFoundException",
    "LoaderException",
    "LoaderNotFoundException",
    "MailConfigurationException",
    "MailDriverException",
    "MailException",
    "MailSendException",
    "MethodNotAllowedException",
    "MiddlewareException",
    "MiddlewareNotFoundException",
    "MigrationException",
    "MissingContainerBindingException",
    "ModelException",
    "ModelNotFoundException",
    "MultipleRecordsFoundException",
    "ORMException",
    "PayloadTooLargeException",
    "QueryException",
    "QueueConfigurationException",
    "QueueDriverLibraryNotFoundException",
    "QueueException",
    "RateLimitConfigurationException",
    "ResponseException",
    "RouteException",
    "RouteMiddlewareNotFoundException",
    "RouteNotFoundException",
    "RouteRegistrationException",
    "RuleNotFoundException",
    "SchedulingConfigurationException",
    "SchedulingException",
    "SchemaPlanRefused",
    "ScratchDatabaseException",
    "ServiceUnavailableException",
    "StorageConfigurationException",
    "StorageException",
    "StrictContainerException",
    "TokenBlacklistedException",
    "TokenExpiredException",
    "TokenInvalidException",
    "UnsupportedMediaTypeException",
    "UserNotFoundException",
    "ValidationException",
    "WebSocketException",
    "validate_exception_envelopes",
]

_install_lazy_exports(__name__, _LAZY_EXPORTS)

# Imported after every exception name is bound. ``ExceptionProvider`` itself
# keeps the HTTP handler lazy, so this canonical class export is cold-import
# safe and can never be shadowed by its same-named submodule.
from .ExceptionProvider import ExceptionProvider  # noqa: E402
