"""Queues — layer barrel (generated, DOCTRINE §5.1)."""

from cara._LazyExports import _install_lazy_exports

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "AMQPDriver": (".drivers", "AMQPDriver"),
    "AMQP_MAX_PRIORITY": (".BrokerConfig", "AMQP_MAX_PRIORITY"),
    "AMQP_PRIORITY_LEVELS": (".BrokerConfig", "AMQP_PRIORITY_LEVELS"),
    "Any": (".middleware", "Any"),
    "BaseJob": (".contracts", "BaseJob"),
    "BaseQueueable": (".contracts", "BaseQueueable"),
    "Bus": (".Bus", "Bus"),
    "Callable": (".middleware", "Callable"),
    "CancellableJob": (".contracts", "CancellableJob"),
    "ConcurrencyBackendUnavailable": (".middleware", "ConcurrencyBackendUnavailable"),
    "ConcurrencyExceeded": (".middleware", "ConcurrencyExceeded"),
    "ConcurrencyLimited": (".middleware", "ConcurrencyLimited"),
    "DEAD_LETTER_BINDING": (".QueueState", "DEAD_LETTER_BINDING"),
    "DEAD_LETTER_EXCHANGE": (".QueueState", "DEAD_LETTER_EXCHANGE"),
    "DEAD_LETTER_QUEUE": (".QueueState", "DEAD_LETTER_QUEUE"),
    "DEFAULT_MAX_ATTEMPTS": (".retry", "DEFAULT_MAX_ATTEMPTS"),
    "DEFAULT_MAX_THROTTLE_ATTEMPTS": (".retry", "DEFAULT_MAX_THROTTLE_ATTEMPTS"),
    "DEFAULT_RETRY_BACKOFF_SECONDS": (".retry", "DEFAULT_RETRY_BACKOFF_SECONDS"),
    "DEFAULT_RETRY_JITTER_FRACTION": (".retry", "DEFAULT_RETRY_JITTER_FRACTION"),
    "DeliveryClaim": (".delivery", "DeliveryClaim"),
    "DeliveryEnvelopeExpired": (".delivery", "DeliveryEnvelopeExpired"),
    "DeliveryEnvelopeMismatch": (".delivery", "DeliveryEnvelopeMismatch"),
    "DeliveryLeaseLost": (".delivery", "DeliveryLeaseLost"),
    "DurableDelayedJobStore": (".delay", "DurableDelayedJobStore"),
    "JobCancelledException": (".contracts", "JobCancelledException"),
    "JobClassResolver": (".JobClassResolver", "JobClassResolver"),
    "JobContext": (".JobContext", "JobContext"),
    "JobThrottledException": (".contracts", "JobThrottledException"),
    "JobTracker": (".tracking", "JobTracker"),
    "MAX_AMQP_JOB_PAYLOAD_BYTES": (".PayloadLimits", "MAX_AMQP_JOB_PAYLOAD_BYTES"),
    "MakesIdempotentBase": (".idempotency", "MakesIdempotentBase"),
    "MakesRetryable": (".retry", "MakesRetryable"),
    "ONE_WORD": (".routing", "ONE_WORD"),
    "PRIVATE_BROKER_HOSTS": (".BrokerConfig", "PRIVATE_BROKER_HOSTS"),
    "PendingDispatch": (".contracts", "PendingDispatch"),
    "PublicationBacklogProbe": (".delivery", "PublicationBacklogProbe"),
    "Queue": (".Queue", "Queue"),
    "QueueContract": (".contracts", "QueueContract"),
    "QueueJobDeliveryStore": (".delivery", "QueueJobDeliveryStore"),
    "QueueMonitor": (".QueueMonitor", "QueueMonitor"),
    "QueueOperationsStore": (".delivery", "QueueOperationsStore"),
    "QueueOutboxHealth": (".delivery", "QueueOutboxHealth"),
    "QueueProvider": (".QueueProvider", "QueueProvider"),
    "QueueRouter": (".routing", "QueueRouter"),
    "QueueState": (".QueueState", "QueueState"),
    "Queueable": (".contracts", "Queueable"),
    "RateLimited": (".middleware", "RateLimited"),
    "ReplayDelivery": (".delivery", "ReplayDelivery"),
    "RoutingKey": (".routing", "RoutingKey"),
    "SerializesModels": (".contracts", "SerializesModels"),
    "ShouldDispatchAfterCommit": (".contracts", "ShouldDispatchAfterCommit"),
    "ShouldQueue": (".contracts", "ShouldQueue"),
    "SignedJsonJobSerializer": (".serializers", "SignedJsonJobSerializer"),
    "Tenancy": (".middleware", "Tenancy"),
    "TerminalHookClaim": (".delivery", "TerminalHookClaim"),
    "ThrottlesExceptions": (".middleware", "ThrottlesExceptions"),
    "Trackable": (".tracking", "Trackable"),
    "UniqueDeliveryConflict": (".delivery", "UniqueDeliveryConflict"),
    "UniqueJob": (".contracts", "UniqueJob"),
    "WithoutOverlapping": (".middleware", "WithoutOverlapping"),
    "asyncio": (".middleware", "asyncio"),
    "close_quietly": (".QueueState", "close_quietly"),
    "declare_dead_letter_topology": (".QueueState", "declare_dead_letter_topology"),
    "ensure_exact_queue": (".QueueState", "ensure_exact_queue"),
    "format_queue_states": (".QueueState", "format_queue_states"),
    "get_monitor": (".QueueMonitor", "get_monitor"),
    "inspect_queue": (".QueueState", "inspect_queue"),
    "instantiate_job": (".JobInstantiation", "instantiate_job"),
    "matches_pattern": (".routing", "matches_pattern"),
    "patterns_overlap": (".routing", "patterns_overlap"),
    "queue_signing_keyring": (".BrokerConfig", "queue_signing_keyring"),
    "rabbit_broker_access": (".BrokerConfig", "rabbit_broker_access"),
    "rabbit_credentials": (".BrokerConfig", "rabbit_credentials"),
    "rabbit_scheme": (".BrokerConfig", "rabbit_scheme"),
    "require_isolated_vhost": (".BrokerConfig", "require_isolated_vhost"),
    "run_middleware_chain_async": (".middleware", "run_middleware_chain_async"),
    "run_through_middleware": (".middleware", "run_through_middleware"),
    "run_through_middleware_async": (".middleware", "run_through_middleware_async"),
    "safe_dispatch": (".helpers", "safe_dispatch"),
}

__all__ = [
    "AMQPDriver",
    "AMQP_MAX_PRIORITY",
    "AMQP_PRIORITY_LEVELS",
    "Any",
    "BaseJob",
    "BaseQueueable",
    "Bus",
    "Callable",
    "CancellableJob",
    "ConcurrencyBackendUnavailable",
    "ConcurrencyExceeded",
    "ConcurrencyLimited",
    "DEAD_LETTER_BINDING",
    "DEAD_LETTER_EXCHANGE",
    "DEAD_LETTER_QUEUE",
    "DEFAULT_MAX_ATTEMPTS",
    "DEFAULT_MAX_THROTTLE_ATTEMPTS",
    "DEFAULT_RETRY_BACKOFF_SECONDS",
    "DEFAULT_RETRY_JITTER_FRACTION",
    "DeliveryClaim",
    "DeliveryEnvelopeExpired",
    "DeliveryEnvelopeMismatch",
    "DeliveryLeaseLost",
    "DurableDelayedJobStore",
    "JobCancelledException",
    "JobClassResolver",
    "JobContext",
    "JobThrottledException",
    "JobTracker",
    "MAX_AMQP_JOB_PAYLOAD_BYTES",
    "MakesIdempotentBase",
    "MakesRetryable",
    "ONE_WORD",
    "PRIVATE_BROKER_HOSTS",
    "PendingDispatch",
    "PublicationBacklogProbe",
    "Queue",
    "QueueContract",
    "QueueJobDeliveryStore",
    "QueueMonitor",
    "QueueOperationsStore",
    "QueueOutboxHealth",
    "QueueProvider",
    "QueueRouter",
    "QueueState",
    "Queueable",
    "RateLimited",
    "ReplayDelivery",
    "RoutingKey",
    "SerializesModels",
    "ShouldDispatchAfterCommit",
    "ShouldQueue",
    "SignedJsonJobSerializer",
    "Tenancy",
    "TerminalHookClaim",
    "ThrottlesExceptions",
    "Trackable",
    "UniqueDeliveryConflict",
    "UniqueJob",
    "WithoutOverlapping",
    "asyncio",
    "close_quietly",
    "declare_dead_letter_topology",
    "ensure_exact_queue",
    "format_queue_states",
    "get_monitor",
    "inspect_queue",
    "instantiate_job",
    "matches_pattern",
    "patterns_overlap",
    "queue_signing_keyring",
    "rabbit_broker_access",
    "rabbit_credentials",
    "rabbit_scheme",
    "require_isolated_vhost",
    "run_middleware_chain_async",
    "run_through_middleware",
    "run_through_middleware_async",
    "safe_dispatch",
]

_install_lazy_exports(__name__, _LAZY_EXPORTS)
