"""Dependency-isolated HTTP public API."""

from __future__ import annotations

from cara._LazyExports import _install_lazy_exports

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "BaseResponse": (".response", "BaseResponse"),
    "BodyLimits": (".BodyLimits", "BodyLimits"),
    "ContentTypeDetector": (".response", "ContentTypeDetector"),
    "Controller": (".controllers", "Controller"),
    "FakeExhaustedError": (".client", "FakeExhaustedError"),
    "FormRequest": (".requests", "FormRequest"),
    "Header": (".request", "Header"),
    "HeaderBag": (".request", "HeaderBag"),
    "HeaderManager": (".response", "HeaderManager"),
    "HttpFacade": (".client", "HttpFacade"),
    "HttpFakeState": (".client", "HttpFakeState"),
    "Input": (".request", "Input"),
    "InputBag": (".request", "InputBag"),
    "InvalidCursor": ("cara.exceptions.types.InvalidCursor", "InvalidCursor"),
    "InvalidHTTPStatusCode": (".InvalidHTTPStatusCode", "InvalidHTTPStatusCode"),
    "JsonResource": (".resources", "JsonResource"),
    "KeyPart": (".request", "KeyPart"),
    "MakesBodyParsing": (".request", "MakesBodyParsing"),
    "MakesRequestHelpers": (".request", "MakesRequestHelpers"),
    "MakesValidationHelpers": (".request", "MakesValidationHelpers"),
    "MissingValue": (".resources", "MissingValue"),
    "Pagination": (".Pagination", "Pagination"),
    "PendingRequest": (".client", "PendingRequest"),
    "QueryStringParser": (".request", "QueryStringParser"),
    "Request": (".request", "Request"),
    "RequestProvider": (".request", "RequestProvider"),
    "ResourceCollection": (".resources", "ResourceCollection"),
    "Response": (".response", "Response"),
    "ResponseFactory": (".response", "ResponseFactory"),
    "ResponseProvider": (".response", "ResponseProvider"),
    "StrayHttpRequestError": (".client", "StrayHttpRequestError"),
    "StreamingResponse": (".response", "StreamingResponse"),
    "T": (".request", "T"),
    "UploadedFile": (".request", "UploadedFile"),
    "activate": (".client", "activate"),
    "apply_no_cache": (".CacheHeaders", "apply_no_cache"),
    "apply_private_cache": (".CacheHeaders", "apply_private_cache"),
    "apply_public_swr_cache": (".CacheHeaders", "apply_public_swr_cache"),
    "assert_editable_fields": (".Payload", "assert_editable_fields"),
    "coerce": (".client", "coerce"),
    "current": (".client", "current"),
    "current_request": (".request", "current_request"),
    "cursor_fingerprint": (".Cursor", "cursor_fingerprint"),
    "cursor_rules": (".Cursor", "cursor_rules"),
    "deactivate": (".client", "deactivate"),
    "decode_cursor": (".Cursor", "decode_cursor"),
    "encode_cursor": (".Cursor", "encode_cursor"),
    "make_response": (".client", "make_response"),
    "opt_bool": (".resources", "opt_bool"),
    "opt_datetime": (".resources", "opt_datetime"),
    "opt_float": (".resources", "opt_float"),
    "opt_int": (".resources", "opt_int"),
    "opt_list": (".resources", "opt_list"),
    "opt_str": (".resources", "opt_str"),
    "paging_rules": (".Pagination", "paging_rules"),
    "slice_page_with_lookahead": (".Cursor", "slice_page_with_lookahead"),
    "strip_none_values": (".Payload", "strip_none_values"),
    "validated_query_int": (".Payload", "validated_query_int"),
}

__all__ = [
    "BaseResponse",
    "BodyLimits",
    "ContentTypeDetector",
    "Controller",
    "FakeExhaustedError",
    "FormRequest",
    "Header",
    "HeaderBag",
    "HeaderManager",
    "HttpFacade",
    "HttpFakeState",
    "Input",
    "InputBag",
    "InvalidCursor",
    "InvalidHTTPStatusCode",
    "JsonResource",
    "KeyPart",
    "MakesBodyParsing",
    "MakesRequestHelpers",
    "MakesValidationHelpers",
    "MissingValue",
    "Pagination",
    "PendingRequest",
    "QueryStringParser",
    "Request",
    "RequestProvider",
    "ResourceCollection",
    "Response",
    "ResponseFactory",
    "ResponseProvider",
    "StrayHttpRequestError",
    "StreamingResponse",
    "T",
    "UploadedFile",
    "activate",
    "apply_no_cache",
    "apply_private_cache",
    "apply_public_swr_cache",
    "assert_editable_fields",
    "coerce",
    "current",
    "current_request",
    "cursor_fingerprint",
    "cursor_rules",
    "deactivate",
    "decode_cursor",
    "encode_cursor",
    "make_response",
    "opt_bool",
    "opt_datetime",
    "opt_float",
    "opt_int",
    "opt_list",
    "opt_str",
    "paging_rules",
    "slice_page_with_lookahead",
    "strip_none_values",
    "validated_query_int",
]

_install_lazy_exports(__name__, _LAZY_EXPORTS)
