"""Boot-free public command contracts.

Concrete core commands are discovered from their leaf modules. Importing this
package must not boot every command or its optional runtime dependencies.
"""

from cara._LazyExports import _install_lazy_exports

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "AMQPConnectionManager": (".core", "AMQPConnectionManager"),
    "ActiveJobCancellationRegistry": (".core", "ActiveJobCancellationRegistry"),
    "ArchBarrelsCommand": (".core", "ArchBarrelsCommand"),
    "ArchCheckCommand": (".core", "ArchCheckCommand"),
    "BootlessCommandSpec": (".BootlessCommandSpec", "BootlessCommandSpec"),
    "CacheClearCommand": (".core", "CacheClearCommand"),
    "CheckResult": (".core", "CheckResult"),
    "Command": (".Command", "Command"),
    "CommandBase": (".CommandBase", "CommandBase"),
    "CommandLoader": (".CommandLoader", "CommandLoader"),
    "CommandProvider": (".CommandProvider", "CommandProvider"),
    "CommandRegistry": (".CommandRegistry", "CommandRegistry"),
    "CommandRunner": (".CommandRunner", "CommandRunner"),
    "DEFAULT_LOCK_TIMEOUT_MS": (".core", "DEFAULT_LOCK_TIMEOUT_MS"),
    "DeliverySettlementError": (".core", "DeliverySettlementError"),
    "DevResetCommand": (".core", "DevResetCommand"),
    "DocsCommand": (".core", "DocsCommand"),
    "DocsGenerateCommand": (".core", "DocsGenerateCommand"),
    "DocsServeCommand": (".core", "DocsServeCommand"),
    "DownCommand": (".core", "DownCommand"),
    "FAIL": (".core", "FAIL"),
    "GenerateKeyCommand": (".core", "GenerateKeyCommand"),
    "JobProcessor": (".core", "JobProcessor"),
    "ListCommandsCommand": (".core", "ListCommandsCommand"),
    "MakeControllerCommand": (".core", "MakeControllerCommand"),
    "MakeEventCommand": (".core", "MakeEventCommand"),
    "MakeJobCommand": (".core", "MakeJobCommand"),
    "MakeListenerCommand": (".core", "MakeListenerCommand"),
    "MakeMailCommand": (".core", "MakeMailCommand"),
    "MakeMiddlewareCommand": (".core", "MakeMiddlewareCommand"),
    "MakeMigrationCommand": (".core", "MakeMigrationCommand"),
    "MakeModelCommand": (".core", "MakeModelCommand"),
    "MakeNotificationCommand": (".core", "MakeNotificationCommand"),
    "MakePolicyCommand": (".core", "MakePolicyCommand"),
    "MakesAutoReload": (".MakesAutoReload", "MakesAutoReload"),
    "MigrateBaselineCommand": (".core", "MigrateBaselineCommand"),
    "MigrateCommand": (".core", "MigrateCommand"),
    "MigrateResetCommand": (".core", "MigrateResetCommand"),
    "MigrateRollbackCommand": (".core", "MigrateRollbackCommand"),
    "MigrateStatusCommand": (".core", "MigrateStatusCommand"),
    "MigrationFile": (".core", "MigrationFile"),
    "MigrationsCheckCommand": (".core", "MigrationsCheckCommand"),
    "ModelPruneCommand": (".core", "ModelPruneCommand"),
    "OK": (".core", "OK"),
    "OptionalDependencyError": (".OptionalDependencyError", "OptionalDependencyError"),
    "PreflightCommand": (".core", "PreflightCommand"),
    "QueueFlushCommand": (".core", "QueueFlushCommand"),
    "QueueHookCommand": (".core", "QueueHookCommand"),
    "QueueHooksCommand": (".core", "QueueHooksCommand"),
    "QueueMonitorCommand": (".core", "QueueMonitorCommand"),
    "QueuePurgeCommand": (".core", "QueuePurgeCommand"),
    "QueueRelayCommand": (".core", "QueueRelayCommand"),
    "QueueRetryCommand": (".core", "QueueRetryCommand"),
    "QueueStatsCommand": (".core", "QueueStatsCommand"),
    "QueueWorkCommand": (".core", "QueueWorkCommand"),
    "RouteGeneratorCommand": (".core", "RouteGeneratorCommand"),
    "RouteListCommand": (".core", "RouteListCommand"),
    "ScheduleWorkCommand": (".core", "ScheduleWorkCommand"),
    "SchemaApplyCommand": (".core", "SchemaApplyCommand"),
    "SchemaCheckCommand": (".core", "SchemaCheckCommand"),
    "SchemaPlanCommand": (".core", "SchemaPlanCommand"),
    "SchemaRollbackCommand": (".core", "SchemaRollbackCommand"),
    "SchemaVerifyCommand": (".core", "SchemaVerifyCommand"),
    "ServeCommand": (".core", "ServeCommand"),
    "StorageLinkCommand": (".core", "StorageLinkCommand"),
    "ThreadSafeAMQPAckChannel": (".core", "ThreadSafeAMQPAckChannel"),
    "TinkerCommand": (".core", "TinkerCommand"),
    "UpCommand": (".core", "UpCommand"),
    "VendorCommonsCommand": (".core", "VendorCommonsCommand"),
    "Violation": (".core", "Violation"),
    "WARN": (".core", "WARN"),
    "audit_migrations": (".core", "audit_migrations"),
    "check_app_key_set": (".core", "check_app_key_set"),
    "check_debug_off_in_prod": (".core", "check_debug_off_in_prod"),
    "check_required_config_present": (".core", "check_required_config_present"),
    "dispatch_architecture": (".BootlessCommandSpec", "dispatch_architecture"),
    "dispatch_bootless": (".BootlessCommandSpec", "dispatch_bootless"),
    "fail": (".core", "fail"),
    "main": (".Cli", "main"),
    "missing_optional": (".OptionalDependencyError", "missing_optional"),
    "ok": (".core", "ok"),
    "parse_migration_file": (".core", "parse_migration_file"),
    "warn": (".core", "warn"),
}

__all__ = [
    "AMQPConnectionManager",
    "ActiveJobCancellationRegistry",
    "ArchBarrelsCommand",
    "ArchCheckCommand",
    "BootlessCommandSpec",
    "CacheClearCommand",
    "CheckResult",
    "Command",
    "CommandBase",
    "CommandLoader",
    "CommandProvider",
    "CommandRegistry",
    "CommandRunner",
    "DEFAULT_LOCK_TIMEOUT_MS",
    "DeliverySettlementError",
    "DevResetCommand",
    "DocsCommand",
    "DocsGenerateCommand",
    "DocsServeCommand",
    "DownCommand",
    "FAIL",
    "GenerateKeyCommand",
    "JobProcessor",
    "ListCommandsCommand",
    "MakeControllerCommand",
    "MakeEventCommand",
    "MakeJobCommand",
    "MakeListenerCommand",
    "MakeMailCommand",
    "MakeMiddlewareCommand",
    "MakeMigrationCommand",
    "MakeModelCommand",
    "MakeNotificationCommand",
    "MakePolicyCommand",
    "MakesAutoReload",
    "MigrateBaselineCommand",
    "MigrateCommand",
    "MigrateResetCommand",
    "MigrateRollbackCommand",
    "MigrateStatusCommand",
    "MigrationFile",
    "MigrationsCheckCommand",
    "ModelPruneCommand",
    "OK",
    "OptionalDependencyError",
    "PreflightCommand",
    "QueueFlushCommand",
    "QueueHookCommand",
    "QueueHooksCommand",
    "QueueMonitorCommand",
    "QueuePurgeCommand",
    "QueueRelayCommand",
    "QueueRetryCommand",
    "QueueStatsCommand",
    "QueueWorkCommand",
    "RouteGeneratorCommand",
    "RouteListCommand",
    "ScheduleWorkCommand",
    "SchemaApplyCommand",
    "SchemaCheckCommand",
    "SchemaPlanCommand",
    "SchemaRollbackCommand",
    "SchemaVerifyCommand",
    "ServeCommand",
    "StorageLinkCommand",
    "ThreadSafeAMQPAckChannel",
    "TinkerCommand",
    "UpCommand",
    "VendorCommonsCommand",
    "Violation",
    "WARN",
    "audit_migrations",
    "check_app_key_set",
    "check_debug_off_in_prod",
    "check_required_config_present",
    "dispatch_architecture",
    "dispatch_bootless",
    "fail",
    "main",
    "missing_optional",
    "ok",
    "parse_migration_file",
    "warn",
]

_install_lazy_exports(__name__, _LAZY_EXPORTS)
